force-app/main/default/objects/DistribuicaoVisita__c/DistribuicaoVisita__c.object-meta.xml
<CustomObject>
    <label>Distribuição de visita</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribuições de visita</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DistribuicaoVisita__c/fields/NumeroVidas__c.field-meta.xml
<CustomField>
    <fullName>NumeroVidas__c</fullName>
    <label>Número de Vidas</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DistribuicaoVisita__c/fields/PessoaFisica__c.field-meta.xml
<CustomField>
    <fullName>PessoaFisica__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Atende os Leads dos tipos:
Pessoa Física;
Pessoa Física RN; 
Médico cooperado;</inlineHelpText>
    <label>Pessoa Fisica</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DistribuicaoVisita__c/fields/PessoaJuridica__c.field-meta.xml
<CustomField>
    <fullName>PessoaJuridica__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Atende os Leads Pessoa Jurídica conforme faixa de números de vidas que atende os portes:
PME2;
ME;
GC;
CE;</inlineHelpText>
    <label>Pessoa Jurídica</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MembroDistribuicaoVisita__c/MembroDistribuicaoVisita__c.object-meta.xml
<CustomObject>
    <label>Membro da distribuição de visita</label>
    <nameField>
        <displayFormat>MDV-{000000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membros da distribuição de visita</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MembroDistribuicaoVisita__c/fields/DistribuicaoVisita__c.field-meta.xml
<CustomField>
    <fullName>DistribuicaoVisita__c</fullName>
    <label>Distribuição de Visita</label>
    <referenceTo>DistribuicaoVisita__c</referenceTo>
    <relationshipLabel>Membros</relationshipLabel>
    <relationshipName>Membros_da_distribuicao_de_visita</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembroDistribuicaoVisita__c/fields/ServiceResource__c.field-meta.xml
<CustomField>
    <fullName>ServiceResource__c</fullName>
    <label>Pessoa</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>ServiceResource.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Membros da distribuição de visita</relationshipLabel>
    <relationshipName>Membros_da_distribuicao_de_visita</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ServicePointGroupComponentControllerTest.cls
@isTest
public class ServicePointGroupComponentControllerTest {

    @testSetup
    static void setup(){

        ServiceResource rsc = new ServiceResource(
            IsActive = true,
            RelatedRecordId = UserInfo.getUserId(),
            Name = 'User1',
            ResourceType = 'T'
        );
        insert rsc;

        DistribuicaoVisita__c dv = new DistribuicaoVisita__c(
            PessoaFisica__c = true,
            PessoaJuridica__c = true,
            Name = 'Primeira Distribuicao',
            NumeroVidas__c = 31
        );
        insert dv;

        MembroDistribuicaoVisita__c mdv = new MembroDistribuicaoVisita__c(
            ServiceResource__c = rsc.Id,
            DistribuicaoVisita__c = dv.Id
        );
        insert mdv;
    }

    @isTest
    static void getAbsenceTypeTest(){
        Test.startTest();
        Map<String, String> response = ServicePointGroupComponentController.getAbsenceType();
        Test.stopTest();
    }

    @isTest
    static void getResourceAbsenceTest(){
        DistribuicaoVisita__c dv = [SELECT Id FROM DistribuicaoVisita__c LIMIT 1];
        MembroDistribuicaoVisita__c mdv = [SELECT Id FROM MembroDistribuicaoVisita__c LIMIT 1];

        Test.startTest();
        List<ResourceAbsence> response1 = ServicePointGroupComponentController.getResourceAbsence(dv.Id);
        List<ResourceAbsence> response2 = ServicePointGroupComponentController.getResourceAbsence(mdv.Id);
        Test.stopTest();
    }

    @isTest
    static void saveAbscences(){
        DistribuicaoVisita__c dv = [SELECT Id FROM DistribuicaoVisita__c LIMIT 1];
        MembroDistribuicaoVisita__c mdv = [SELECT Id FROM MembroDistribuicaoVisita__c LIMIT 1];


        Test.startTest();
        String result1 = ServicePointGroupComponentController.saveAbscences(dv.Id, 'Almoço', Datetime.now(), Datetime.now().addHours(1), 'Descrição');
        String result2 = ServicePointGroupComponentController.saveAbscences(mdv.Id, 'Almoço', Datetime.now().addDays(1), Datetime.now().addDays(1).addHours(1), 'Descrição');
        Test.stopTest();

    }
}