force-app/main/default/objects/DistribuicaoVisita__c/DistribuicaoVisita__c.object-meta.xml
<CustomObject>
    <label>Distribuição de visita</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribuições de visita</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DistribuicaoVisita__c/fields/PessoaFisica__c.field-meta.xml
<CustomField>
    <fullName>PessoaFisica__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Atende os Leads dos tipos:
Pessoa Física;
Pessoa Física RN; 
Médico cooperado;</inlineHelpText>
    <label>Pessoa Fisica</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DistribuicaoVisita__c/fields/PessoaJuridica__c.field-meta.xml
<CustomField>
    <fullName>PessoaJuridica__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Atende os Leads Pessoa Jurídica conforme faixa de números de vidas que atende os portes:
PME2;
ME;
GC;
CE;</inlineHelpText>
    <label>Pessoa Jurídica</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DistribuicaoVisita__c/fields/Porte__c.field-meta.xml
<CustomField>
    <fullName>Porte__c</fullName>
    <formula>CASE(1,

IF((NumeroVidas__c&gt;=1)&amp;&amp;(NumeroVidas__c&lt;=29),1,0),&apos;PME1 e Individual&apos;,

IF((NumeroVidas__c&gt;29)&amp;&amp;(NumeroVidas__c&lt;=99) &amp;&amp;  (CONTAINS(Codigo__c, &apos;EXT&apos;) || CONTAINS(Codigo__c, &apos;INT&apos;)),1,0),&apos;PME1, PME2 e Individual&apos;,

IF((NumeroVidas__c &gt; 29)&amp;&amp; (NumeroVidas__c&lt;=99),1,0), &apos;PME2&apos;,

IF((NumeroVidas__c &gt; 99)&amp;&amp; (NumeroVidas__c&lt;=300),1,0), &apos;ME&apos;,

IF((NumeroVidas__c &gt; 300)&amp;&amp; (NumeroVidas__c&lt;=600),1,0), &apos;GC&apos;,

IF((NumeroVidas__c &gt; 600),1,0), &apos;CE&apos;,

&apos;Dados Inválidos&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Porte</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DistribuicaoVisita__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo de equipe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Call center</fullName>
            </value>
            <value>
                <fullName>Consultores</fullName>
            </value>
            <value>
                <fullName>Equipe corporativa</fullName>
            </value>
            <value>
                <fullName>Loja autorizada</fullName>
            </value>
            <value>
                <fullName>Loja própria</fullName>
            </value>
            <value>
                <fullName>Promotores</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <formula>Latitude</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Latitude</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <formula>Longitude</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Longitude</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/PessoaFisica__c.field-meta.xml
<CustomField>
    <fullName>PessoaFisica__c</fullName>
    <formula>NOT(CONTAINS(TipoAtendimento__c, &apos;Jurídica&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>É pessoa física?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/PessoaJuridica__c.field-meta.xml
<CustomField>
    <fullName>PessoaJuridica__c</fullName>
    <formula>CONTAINS(TipoAtendimento__c, &apos;Jurídica&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>É pessoa jurídica?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Porte__c.field-meta.xml
<CustomField>
    <fullName>Porte__c</fullName>
    <formula>IF(RecordType.Name = &apos;Pessoa Física&apos; || RecordType.Name = &apos;Pessoa Física RN&apos; || RecordType.Name = &apos;Médico Cooperado&apos;,&apos;Individual&apos;,IF(AND(NumeroVidas__c + QtdeVidasTransferencia__c &lt;= 29, RecordType.Name = &apos;Pessoa Jurídica&apos; || RecordType.Name = &apos;Pessoa Jurídica - Enterprise&apos; ), &apos;PME1&apos;,IF(NumeroVidas__c + QtdeVidasTransferencia__c &lt;= 99, &apos;PME2&apos;,IF(NumeroVidas__c + QtdeVidasTransferencia__c &lt;= 300, &apos;ME&apos;,IF(NumeroVidas__c + QtdeVidasTransferencia__c &lt;= 600, &apos;GC&apos;,IF(NumeroVidas__c + QtdeVidasTransferencia__c &gt; 600, &apos;CE&apos;,&apos;&apos;))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Porte</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MembroDistribuicaoVisita__c/MembroDistribuicaoVisita__c.object-meta.xml
<CustomObject>
    <label>Membro da distribuição de visita</label>
    <nameField>
        <displayFormat>MDV-{000000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membros da distribuição de visita</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MembroDistribuicaoVisita__c/fields/DistribuicaoVisita__c.field-meta.xml
<CustomField>
    <fullName>DistribuicaoVisita__c</fullName>
    <label>Distribuição de Visita</label>
    <referenceTo>DistribuicaoVisita__c</referenceTo>
    <relationshipLabel>Membros</relationshipLabel>
    <relationshipName>Membros_da_distribuicao_de_visita</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembroDistribuicaoVisita__c/fields/ServiceResource__c.field-meta.xml
<CustomField>
    <fullName>ServiceResource__c</fullName>
    <label>Pessoa</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>ServiceResource.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Membros da distribuição de visita</relationshipLabel>
    <relationshipName>Membros_da_distribuicao_de_visita</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RastreamentoRecursoServico__b/RastreamentoRecursoServico__b.object-meta.xml
<CustomObject>
    <label>Rastreamento do recurso de serviço</label>
    <pluralLabel>Rastreamentos do recurso de serviço</pluralLabel>
</CustomObject>

force-app/main/default/objects/RastreamentoRecursoServico__b/fields/DataLocalizacao__c.field-meta.xml
<CustomField>
    <fullName>DataLocalizacao__c</fullName>
    <label>Data de localização</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RastreamentoRecursoServico__b/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RastreamentoRecursoServico__b/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RastreamentoRecursoServico__b/fields/ServiceResource__c.field-meta.xml
<CustomField>
    <fullName>ServiceResource__c</fullName>
    <label>ServiceResource</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Visitas</relationshipLabel>
    <relationshipName>CompromissosServicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Porte__c.field-meta.xml
<CustomField>
    <fullName>Porte__c</fullName>
    <formula>CASE(1,
IF((NumeroVidas__c=1)&amp;&amp;( Lead__r.RecordType.Name = &apos;Pessoa Física&apos; || Lead__r.RecordType.Name = &apos;Pessoa Física RN&apos; || Lead__r.RecordType.Name = &apos;Médico Cooperado&apos;),1,0),&apos;Individual&apos;,

IF((NumeroVidas__c=1)&amp;&amp;( Lead__r.RecordType.Name = &apos;Pessoa Jurídica&apos; || Lead__r.RecordType.Name = &apos;Pessoa Jurídica - Enterprise&apos;),1,0),&apos;PME1&apos;,

IF((NumeroVidas__c&gt;=2)&amp;&amp;(NumeroVidas__c&lt;=29),1,0),&apos;PME&apos;,

IF((NumeroVidas__c &gt; 29)&amp;&amp; (NumeroVidas__c&lt;=99),1,0), &apos;PME2&apos;,

IF((NumeroVidas__c &gt; 99)&amp;&amp; (NumeroVidas__c&lt;=300),1,0), &apos;ME&apos;,

IF((NumeroVidas__c &gt; 300)&amp;&amp; (NumeroVidas__c&lt;=600),1,0), &apos;GC&apos;,

IF((NumeroVidas__c &gt; 600),1,0), &apos;CE&apos;,

&apos; &apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Porte</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/ServiceResource__c.field-meta.xml
<CustomField>
    <fullName>ServiceResource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurso de serviço</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Compromissos de serviços</relationshipLabel>
    <relationshipName>Compromissos_de_servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceResource/fields/MinutosUltimaLocalizacao__c.field-meta.xml
<CustomField>
    <fullName>MinutosUltimaLocalizacao__c</fullName>
    <formula>IF(
NOW() - LastKnownLocationDate &gt; 0 ,
(NOW() - LastKnownLocationDate ) * 24 * 60,
0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Minutos da Última Localização</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <inlineHelpText>Informe se a região é uma Cidade ou Bairro.</inlineHelpText>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cidade</fullName>
            </value>
            <value>
                <fullName>Bairro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/DistribuicaoVisita__c.field-meta.xml
<CustomField>
    <fullName>DistribuicaoVisita__c</fullName>
    <label>Distribuição de visita</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/FiltrosRastreamentoGeo2__c.field-meta.xml
<CustomField>
    <fullName>FiltrosRastreamentoGeo2__c</fullName>
    <inlineHelpText>Histórico de filtros utilizados na tela &quot;Rastreamento Geográfico&quot;</inlineHelpText>
    <label>Filtros Rastreamento Geo 2</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/User/fields/FiltrosRastreamentoGeo__c.field-meta.xml
<CustomField>
    <fullName>FiltrosRastreamentoGeo__c</fullName>
    <inlineHelpText>Histórico dos últimos filtros utilizados na tela &quot;Rastreamento Geográfico&quot;</inlineHelpText>
    <label>Filtros Rastreamento Geo</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/MapGeographicController.cls
public with sharing class MapGeographicController {

    @AuraEnabled(cacheable=true)
    public static Boolean checkPermissionMap(){
        return FeatureManagement.checkPermission('FSL_Mapa_Rastreamento_Geografico');
    }

    @AuraEnabled
    public static List<String> verificarFiltrosAnteriores() {
        
        User usuario = [SELECT Id, FiltrosRastreamentoGeo__c, FiltrosRastreamentoGeo2__c FROM User WHERE Id = :UserInfo.getUserId()];
        String filtros1 = usuario.FiltrosRastreamentoGeo__c != null ? usuario.FiltrosRastreamentoGeo__c : '{}';
        String filtros2 = usuario.FiltrosRastreamentoGeo2__c != null ? usuario.FiltrosRastreamentoGeo2__c : '{}';
        List<String> filtros = new List<String>();
        filtros.add(filtros1);
        filtros.add(filtros2);
                
        return filtros;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<ServiceResource> obtainServiceResource(Boolean isFisica, Boolean isJuridica, List<String> tipo, List<String> porte, String serviceTerritoryId){
    
        List<MembroDistribuicaoVisita__c> membros = [SELECT Id, 
                                                        ServiceResource__c 
                                                        FROM MembroDistribuicaoVisita__c 
                                                        WHERE (DistribuicaoVisita__r.PessoaFisica__c = :isFisica 
                                                        OR (DistribuicaoVisita__r.PessoaJuridica__c = :isJuridica AND DistribuicaoVisita__r.Porte__c IN :porte))
                                                        AND DistribuicaoVisita__r.Tipo__c IN :tipo];
     
        Set<Id> resourceId = new Set<Id>();
        for(MembroDistribuicaoVisita__c membro : membros){
            resourceId.add(membro.ServiceResource__c);
        }

        //Filter by Territory
        if(String.isNotBlank(serviceTerritoryId)){
            Set<Id> serviceTerritoryIds = new Set<Id>();
            
            serviceTerritoryIds.add(serviceTerritoryId);
            for(ServiceTerritory serTerri : [SELECT Id, ParentTerritoryId FROM ServiceTerritory WHERE Id = :serviceTerritoryId]){
                serviceTerritoryIds.add(serTerri.ParentTerritoryId);
            }

            Set<Id> resourceIdTerritory = new Set<Id>();
            for(ServiceTerritoryMember member : [SELECT Id, ServiceResourceId, ServiceTerritoryId FROM ServiceTerritoryMember WHERE ServiceResourceId IN :resourceId AND ServiceTerritoryId IN :serviceTerritoryIds]){
                resourceIdTerritory.add(member.ServiceResourceId);
            }

            resourceId = resourceIdTerritory;
        }
                
        return [SELECT Id, Name, LastKnownLatitude, LastKnownLongitude, LastKnownLocationDate, MinutosUltimaLocalizacao__c FROM ServiceResource WHERE LastKnownLocationDate != null AND Id IN :resourceId];
    }

    @AuraEnabled
    public static void salvarFiltros(Boolean isFisica, Boolean isJuridica, List<String> tipo, List<String> porte, String serviceTerritoryId, String serviceResourceId, String inicio, String fim) {

        FiltrosRastreamento fr = new FiltrosRastreamento();
        fr.isFisica = isFisica;
        fr.isJuridica = isJuridica;
        fr.tipo = tipo;
        fr.porte = porte;
        fr.serviceTerritoryId = serviceTerritoryId;
        String filtros1 = JSON.serialize(fr);
        FiltrosRastreamento2 fr2 = new FiltrosRastreamento2();
        fr2.inicio = inicio;
        fr2.fim = fim;
        fr2.serviceResourceId = serviceResourceId;
        String filtros2 = JSON.serialize(fr2);

        User usuario = new User(Id = UserInfo.getUserId());
        usuario.FiltrosRastreamentoGeo__c = filtros1;
        usuario.FiltrosRastreamentoGeo2__c = filtros2;
        update usuario;
    }

    @AuraEnabled(cacheable=true)
    public static List<RastreamentoRecursoServico__b> obtainLocations(String serviceResourceId, String inicio, String fim) {

        Datetime dateInitial = Datetime.valueOf(inicio + ' 00:00:00');
        Datetime dateFinal = Datetime.valueOf(fim + ' 00:00:00');
        dateFinal = dateFinal.addDays(1);

        if (serviceResourceId == null) {

            Map<Id, ServiceResource> mapServiceResources = new Map<Id, ServiceResource>([SELECT Id FROM ServiceResource]);

            return [SELECT ServiceResource__c, DataLocalizacao__c, Latitude__c, Longitude__c FROM RastreamentoRecursoServico__b 
                WHERE ServiceResource__c IN :mapServiceResources.keySet()
                AND DataLocalizacao__c >= :dateInitial 
                AND DataLocalizacao__c < :dateFinal];
        }
                
        return [SELECT ServiceResource__c, DataLocalizacao__c, Latitude__c, Longitude__c FROM RastreamentoRecursoServico__b 
        WHERE ServiceResource__c = :serviceResourceId 
        AND DataLocalizacao__c >= :dateInitial 
        AND DataLocalizacao__c < :dateFinal];
    }

    @AuraEnabled(cacheable=true)
    public static List<ServiceAppointment> obtainServiceAppointment(String serviceResourceId, String inicio, String fim) {

        Datetime dateInitial = Datetime.valueOf(inicio + ' 00:00:00');
        Datetime dateFinal = Datetime.valueOf(fim + ' 00:00:00');
        dateFinal = dateFinal.addDays(1);

        String query = 'SELECT Id, ServiceAppointmentId, ServiceResourceId FROM AssignedResource ' + 
            'WHERE ServiceAppointment.SchedStartTime >= :dateInitial AND ServiceAppointment.SchedStartTime < :dateFinal';
        if (serviceResourceId != null) {
            query += ' AND ServiceResourceId = :serviceResourceId';
        }
        List<AssignedResource> assigneds = Database.query(query);
        
        /*
        List<AssignedResource> assigneds = [SELECT Id, ServiceAppointmentId, ServiceResourceId 
        FROM AssignedResource 
        WHERE ServiceAppointment.SchedStartTime >= :dateInitial AND
        ServiceAppointment.SchedStartTime < :dateFinal AND
        ServiceResourceId = :serviceResourceId];*/

        Set<Id> serviceAppointmentIds = new Set<Id>();
        for(AssignedResource ass : assigneds){
            serviceAppointmentIds.add(ass.ServiceAppointmentId);
        }
        
        return [SELECT Id, Status, SchedStartTime, ActualStartTime, Lead__c, Lead__r.Name, Lead__r.Status, Lead__r.Phone, Lead__r.Latitude, Lead__r.Longitude, Lead__r.Street, Lead__r.State, Lead__r.City, Lead__r.PostalCode, Lead__r.Country, Lead__r.Coordenadas__Latitude__s, Lead__r.Coordenadas__Longitude__s FROM ServiceAppointment WHERE Id IN :serviceAppointmentIds];
    }

    public class FiltrosRastreamento {

        public Boolean isFisica {get;set;}
        public Boolean isJuridica {get;set;}
        public List<String> tipo {get;set;}
        public List<String> porte {get;set;}
        public String serviceTerritoryId {get;set;}
    }

    public class FiltrosRastreamento2 {

        public String inicio {get;set;}
        public String fim {get;set;}
        public String serviceResourceId {get;set;}
    }
}