force-app/main/default/objects/DistribuicaoVisita__c/DistribuicaoVisita__c.object-meta.xml
<CustomObject>
    <label>Distribuição de visita</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribuições de visita</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DistribuicaoVisita__c/fields/NumeroVidas__c.field-meta.xml
<CustomField>
    <fullName>NumeroVidas__c</fullName>
    <label>Número de Vidas</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormaDistribuicao__c/FormaDistribuicao__c.object-meta.xml
<CustomObject>
    <description>Utilizado para gerenciar o processo de distribuição dos leads. Possui os campos quantidade atual, que reflete a quantidade de leads que já foram direcionados a um tipo de carteira, e quantidade máxima, que é o limite definido para mudança do destinatário dos leads.</description>
    <label>Forma de distribuição</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formas de distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FormaDistribuicao__c/fields/QuantidadeAtual__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeAtual__c</fullName>
    <label>Quantidade atual</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormaDistribuicao__c/fields/QuantidadePermitida__c.field-meta.xml
<CustomField>
    <fullName>QuantidadePermitida__c</fullName>
    <label>Quantidade permitida</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Atendente__c.field-meta.xml
<CustomField>
    <fullName>Atendente__c</fullName>
    <inlineHelpText>Informe quem está realizando o cadastro.
Destinado para usuários do call center.</inlineHelpText>
    <label>Atendente</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALINE QUARESMA DA SILVA</fullName>
            </value>
            <value>
                <fullName>ALLAN JUNIO DA COSTA SILVA</fullName>
            </value>
            <value>
                <fullName>BRUNA ISABELLA LEANDRO DA SILVA SANTANA</fullName>
            </value>
            <value>
                <fullName>CAROLINA MENDES BAIA DE CARVALHO</fullName>
            </value>
            <value>
                <fullName>DANIELA FERREIRA DA SILVA</fullName>
            </value>
            <value>
                <fullName>DARLENE APARECIDA ANDRADE SILVA</fullName>
            </value>
            <value>
                <fullName>DEBORA STEFANY SOUZA</fullName>
            </value>
            <value>
                <fullName>EDUARDA ANDRADE FERREIRA</fullName>
            </value>
            <value>
                <fullName>ELIZANGELA DE LOURDES DA SILVA FREITAS</fullName>
            </value>
            <value>
                <fullName>ESTHER CAROLAINE MARTINS DE SOUZA</fullName>
            </value>
            <value>
                <fullName>FERNANDA CONCEICAO PEREIRA</fullName>
            </value>
            <value>
                <fullName>GIULIA MAGALHAES SANTOS</fullName>
            </value>
            <value>
                <fullName>HELOISA BATISTA HONORIO</fullName>
            </value>
            <value>
                <fullName>HUDSON BRENO SANTOS AGANETE ANDRADE</fullName>
            </value>
            <value>
                <fullName>ISABELE MONTEIRO GONCALVES</fullName>
            </value>
            <value>
                <fullName>ISADORA MULLER DE OLIVEIRA</fullName>
            </value>
            <value>
                <fullName>JAISON FERNANDO FERREIRA DA SILVA</fullName>
            </value>
            <value>
                <fullName>JUCYMARA FERREIRA CORREIA</fullName>
            </value>
            <value>
                <fullName>LEONARDO RODRIGUES MARIANO</fullName>
            </value>
            <value>
                <fullName>LUCELIA RABELO COSTA SILVA</fullName>
            </value>
            <value>
                <fullName>RAFAEL REIS DA SILVA</fullName>
            </value>
            <value>
                <fullName>RENAN MARCOS MATOZINHOS SILVA</fullName>
            </value>
            <value>
                <fullName>RODRIGO DORNELLAS DE PINHO</fullName>
            </value>
            <value>
                <fullName>SHANDEL REIS MENEZES</fullName>
            </value>
            <value>
                <fullName>ISABELA CRISTINA SILVA SCHINAIDER</fullName>
            </value>
            <value>
                <fullName>ANA CAROLINA SILVA SOARES</fullName>
            </value>
            <value>
                <fullName>INES CRISTINA DE ARAUJO</fullName>
            </value>
            <value>
                <fullName>EZEQUIEL JUNIO DA SILVA</fullName>
            </value>
            <value>
                <fullName>LARISSA MILENY DE PAIVA SILVA</fullName>
            </value>
            <value>
                <fullName>NATIELLE DE ASSIS CARVALHO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Bairro__c.field-meta.xml
<CustomField>
    <fullName>Bairro__c</fullName>
    <label>Bairro</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <defaultValue>&quot;naotem@naotem.com&quot;</defaultValue>
    <inlineHelpText>Campo utilizado para o Marketing, não modificar o valor padrão.</inlineHelpText>
    <label>Email do cliente</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/NumeroVidas__c.field-meta.xml
<CustomField>
    <fullName>NumeroVidas__c</fullName>
    <label>Quantidade de Vidas Novas</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MembroDistribuicaoVisita__c/MembroDistribuicaoVisita__c.object-meta.xml
<CustomObject>
    <label>Membro da distribuição de visita</label>
    <nameField>
        <displayFormat>MDV-{000000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membros da distribuição de visita</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MembroDistribuicaoVisita__c/fields/DistribuicaoVisita__c.field-meta.xml
<CustomField>
    <fullName>DistribuicaoVisita__c</fullName>
    <label>Distribuição de Visita</label>
    <referenceTo>DistribuicaoVisita__c</referenceTo>
    <relationshipLabel>Membros</relationshipLabel>
    <relationshipName>Membros_da_distribuicao_de_visita</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembroDistribuicaoVisita__c/fields/ServiceResource__c.field-meta.xml
<CustomField>
    <fullName>ServiceResource__c</fullName>
    <label>Pessoa</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>ServiceResource.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Membros da distribuição de visita</relationshipLabel>
    <relationshipName>Membros_da_distribuicao_de_visita</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Atendente__c.field-meta.xml
<CustomField>
    <fullName>Atendente__c</fullName>
    <label>Atendente</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALINE QUARESMA DA SILVA</fullName>
            </value>
            <value>
                <fullName>ALLAN JUNIO DA COSTA SILVA</fullName>
            </value>
            <value>
                <fullName>BRUNA ISABELLA LEANDRO DA SILVA SANTANA</fullName>
            </value>
            <value>
                <fullName>CAROLINA MENDES BAIA DE CARVALHO</fullName>
            </value>
            <value>
                <fullName>DANIELA FERREIRA DA SILVA</fullName>
            </value>
            <value>
                <fullName>DARLENE APARECIDA ANDRADE SILVA</fullName>
            </value>
            <value>
                <fullName>DEBORA STEFANY SOUZA</fullName>
            </value>
            <value>
                <fullName>EDUARDA ANDRADE FERREIRA</fullName>
            </value>
            <value>
                <fullName>ELIZANGELA DE LOURDES DA SILVA FREITAS</fullName>
            </value>
            <value>
                <fullName>ESTHER CAROLAINE MARTINS DE SOUZA</fullName>
            </value>
            <value>
                <fullName>FERNANDA CONCEICAO PEREIRA</fullName>
            </value>
            <value>
                <fullName>GIULIA MAGALHAES SANTOS</fullName>
            </value>
            <value>
                <fullName>HELOISA BATISTA HONORIO</fullName>
            </value>
            <value>
                <fullName>HUDSON BRENO SANTOS AGANETE ANDRADE</fullName>
            </value>
            <value>
                <fullName>ISABELE MONTEIRO GONCALVES</fullName>
            </value>
            <value>
                <fullName>ISADORA MULLER DE OLIVEIRA</fullName>
            </value>
            <value>
                <fullName>JAISON FERNANDO FERREIRA DA SILVA</fullName>
            </value>
            <value>
                <fullName>JUCYMARA FERREIRA CORREIA</fullName>
            </value>
            <value>
                <fullName>LEONARDO RODRIGUES MARIANO</fullName>
            </value>
            <value>
                <fullName>LUCELIA RABELO COSTA SILVA</fullName>
            </value>
            <value>
                <fullName>RAFAEL REIS DA SILVA</fullName>
            </value>
            <value>
                <fullName>RENAN MARCOS MATOZINHOS SILVA</fullName>
            </value>
            <value>
                <fullName>RODRIGO DORNELLAS DE PINHO</fullName>
            </value>
            <value>
                <fullName>SHANDEL REIS MENEZES</fullName>
            </value>
            <value>
                <fullName>ISABELA CRISTINA SILVA SCHINAIDER</fullName>
            </value>
            <value>
                <fullName>ANA CAROLINA SILVA SOARES</fullName>
            </value>
            <value>
                <fullName>INES CRISTINA DE ARAUJO</fullName>
            </value>
            <value>
                <fullName>EZEQUIEL JUNIO DA SILVA</fullName>
            </value>
            <value>
                <fullName>LARISSA MILENY DE PAIVA SILVA</fullName>
            </value>
            <value>
                <fullName>NATIELLE DE ASSIS CARVALHO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Bairro__c.field-meta.xml
<CustomField>
    <fullName>Bairro__c</fullName>
    <label>Bairro</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Visitas</relationshipLabel>
    <relationshipName>CompromissosServicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/NumeroVidas__c.field-meta.xml
<CustomField>
    <fullName>NumeroVidas__c</fullName>
    <formula>Lead__r.NumeroVidas__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Número de Vidas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/ServiceResource__c.field-meta.xml
<CustomField>
    <fullName>ServiceResource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurso de serviço</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Compromissos de serviços</relationshipLabel>
    <relationshipName>Compromissos_de_servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/Bairro__c.field-meta.xml
<CustomField>
    <fullName>Bairro__c</fullName>
    <label>Bairro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/EmailsInteressados__c.field-meta.xml
<CustomField>
    <fullName>EmailsInteressados__c</fullName>
    <label>Emails Interessados</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Agendamentos</relationshipLabel>
    <relationshipName>Agendamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Bairro__c.field-meta.xml
<CustomField>
    <fullName>Bairro__c</fullName>
    <description>Campo fórmula para obter e disponibilizar os bairros dos leads relacionados, dentro das atas.</description>
    <formula>Lead__r.Bairro__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bairro</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Campo fórmula para obter e disponibilizar os e-mails dos leads relacionados, dentro das atas.</description>
    <formula>Lead__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Atas</relationshipLabel>
    <relationshipName>Atas2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/NumeroVidas__c.field-meta.xml
<CustomField>
    <fullName>NumeroVidas__c</fullName>
    <description>Numero de pessoas que possuem plano</description>
    <label>Numero de vidas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/recordTypes/Call.recordType-meta.xml
<RecordType>
    <fullName>Call</fullName>
    <active>true</active>
    <label>Call</label>
</RecordType>

force-app/main/default/objects/WorkOrderLineItem/recordTypes/ClienteAusente.recordType-meta.xml
<RecordType>
    <fullName>ClienteAusente</fullName>
    <active>true</active>
    <label>Cliente Ausente</label>
</RecordType>

force-app/main/default/classes/ScheduleCampaignControllerTest.cls
@isTest
public class ScheduleCampaignControllerTest {
    
    @testSetup
    static void setup(){
        Profile p = [SELECT Id FROM Profile WHERE Name LIKE '%Atendente Call Center%' LIMIT 1]; 
    	User u = new User(
            Alias = 'callc', 
            Email='callcenter@testorg.com', 
            EmailEncodingKey='UTF-8', 
            LastName='callcenter', 
            LanguageLocaleKey='en_US',        
            LocaleSidKey='en_US', 
            ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', 
            UserName='callcenter@testorgtest.com'
        );
        insert u;

        Lead ld = new Lead(
            LastName = 'MyLead',
            MobilePhone = '31988887777',
            Status = 'Captação',
            Email = 'mylead@email.com.br.test',
           // Email__c = 'mylead@email.com.br.test',
            NumeroVidas__c = 31,
            Bairro__c = 'Centro',
            City = 'Belo Horizonte',
            Atendente__c = 'ALINE QUARESMA DA SILVA'
        );
        System.runAs(u){
            insert ld;
        }

        WorkOrder wo = new WorkOrder(
            Status = 'New',
            Lead__c = ld.Id,
            EmailsInteressados__c = 'emailtest@email.com.br.test'
        );
        System.runAs(u){
            insert wo;
        }

      /*  String call = Schema.SObjectType.WorkOrderLineItem.getRecordTypeInfosByDeveloperName().get('Call').getRecordTypeId();
        String clienteAusente = Schema.SObjectType.WorkOrderLineItem.getRecordTypeInfosByDeveloperName().get('ClienteAusente').getRecordTypeId();

        WorkOrderLineItem woli1 = new WorkOrderLineItem(
            WorkOrderId = wo.Id,
            Lead__c = ld.Id,       
            Status = 'New',
            RecordTypeId = call
        );
        insert woli1;

        WorkOrderLineItem woli2 = new WorkOrderLineItem(
            WorkOrderId = wo.Id,
            Lead__c = ld.Id,       
            Status = 'New',
            RecordTypeId = clienteAusente
        );
        insert woli2;*/

        ServiceResource rsc = new ServiceResource(
            IsActive = true,
            RelatedRecordId = UserInfo.getUserId(),
            Name = 'User1',
            ResourceType = 'T'
        );
        insert rsc;

        ServiceAppointment appt = new ServiceAppointment(
            ParentRecordId = wo.Id,
            EarliestStartTime = System.now().addDays(7),
            DueDate = System.now().addDays(8),
            ActualStartTime = System.now().addDays(7),
            ServiceResource__c = rsc.Id
        );
        insert appt;

        Id terrId = createTerritory(rsc.Id);
        createUser(terrId);
        createDistribuicaoVisitas(rsc.Id, terrId);


        List<FormaDistribuicao__c> formasToInsert = new List<FormaDistribuicao__c>();
        formasToInsert.add(new FormaDistribuicao__c(Name='Loja autorizada', QuantidadeAtual__c = 0, QuantidadePermitida__c = 10));
        formasToInsert.add(new FormaDistribuicao__c(Name='Loja própria', QuantidadeAtual__c = 0, QuantidadePermitida__c = 10));
        insert formasToInsert;

    }

    static Id createTerritory(Id srId){
        OperatingHours oh = new OperatingHours(
            Name = 'MyOpHours'
        );
        insert oh;

        createTimeSlots(oh.Id);

        ServiceTerritory terr = new ServiceTerritory(
            Name = 'Belo Horizonte',
            OperatingHoursId = oh.Id,
            IsActive = true
        );
        insert terr;

        ServiceTerritory terr2 = new ServiceTerritory(
            Name = 'Centro',
            OperatingHoursId = oh.Id,
            IsActive = true,
            ParentTerritoryId = terr.Id
        );
        insert terr2;
        
        ServiceTerritoryMember mterr = new ServiceTerritoryMember(
            ServiceResourceId = srId,
            ServiceTerritoryId = terr2.Id,
            EffectiveStartDate = System.now(),
            TerritoryType = 'P'
        );
        insert mterr;


        return terr2.Id;
    }

    static void createTimeSlots(Id OperatingHoursId){

        List<String> days = new List<String>{'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'};

        List<TimeSlot> tss = new List<TimeSlot>();

        for(String day : days){
            TimeSlot ts = new TimeSlot(
                OperatingHoursId = OperatingHoursId,
                DayOfWeek = day,
                StartTime = Time.newInstance(0, 0, 0, 0),
                EndTime = Time.newInstance(23, 59, 59, 0)   
            );
            
            tss.add(ts);
        }
        
        insert tss;
    }

    static void createUser(Id terrId){
        Profile p = [SELECT Id FROM Profile WHERE Name LIKE '%Admin%' LIMIT 1]; 
    	User u = new User(
            Alias = 'standt', 
            Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', 
            LastName='Testing', 
            LanguageLocaleKey='en_US',        
            LocaleSidKey='en_US', 
            ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', 
            UserName='testusertest@testorgtest.com'
        );
        insert u;

    	User u2 = new User(
            Alias = 'standt2', 
            Email='standarduser2@testorg.com', 
            EmailEncodingKey='UTF-8', 
            LastName='Testing2', 
            LanguageLocaleKey='en_US',        
            LocaleSidKey='en_US', 
            ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', 
            UserName='testusertest2@testorgtest.com'
        );
        insert u2;

        ServiceResource rsc = new ServiceResource(
            IsActive = true,
            RelatedRecordId = u2.Id,
            Name = 'User2',
            ResourceType = 'T'
        );
        insert rsc;

        createDistribuicaoVisitas(rsc.Id, terrId);
    }

    static void createDistribuicaoVisitas(Id srId, Id terrId){
        DistribuicaoVisita__c dv = new DistribuicaoVisita__c(
            PessoaFisica__c = true,
            PessoaJuridica__c = true,
            Name = 'Primeira Distribuicao',
            NumeroVidas__c = 31
        );
        insert dv;

        MembroDistribuicaoVisita__c mdv = new MembroDistribuicaoVisita__c(
            ServiceResource__c = srId,
            DistribuicaoVisita__c = dv.Id
        );
        insert mdv;

        RegionalizacaoDistribuicaoVisita__c rdv = new RegionalizacaoDistribuicaoVisita__c(
            ServiceTerritory__c = terrId,
            DistribuicaoVisita__c = dv.Id
        );
        insert rdv;
    }

    @isTest
    static void getTerritoryInfo(){

        Lead ld = [SELECT Id FROM Lead LIMIT 1];

        Test.startTest();
        Map <String, Object> response = ScheduleCampaignController.getTerritoryInfo(ld.Id, true, new List<String>());
        Test.stopTest();

    }

    /*
    @isTest
    static void getTerritoryInfo2(){

        Lead ld = [SELECT Id FROM Lead LIMIT 1];
        ServiceAppointment appt = [SELECT Id FROM ServiceAppointment LIMIT 1];

        appt.SchedStartTime = System.now().addDays(7);
        appt.SchedEndTime = System.now().addDays(8);
        appt.Status = 'Scheduled';

        update appt;

        Test.startTest();
        Map <String, Object> response = ScheduleCampaignController.getTerritoryInfo(ld.Id, true, new List<String>());
        Test.stopTest();

    }
*/

    @isTest
    static void getTerritoryInfo3(){
        User u = [SELECT Id FROM User WHERE Email = 'standarduser@testorg.com' LIMIT 1];
        Lead ld = [SELECT Id FROM Lead LIMIT 1];

        Test.startTest();
        System.runas(u) 
		{
            Map <String, Object> response = ScheduleCampaignController.getTerritoryInfo(ld.Id, true, new List<String>());
            delete [SELECT Id FROM DistribuicaoVisita__c];
            Map <String, Object> response2 = ScheduleCampaignController.getTerritoryInfo(ld.Id, true, new List<String>());
        }
        Test.stopTest();

    }

    @isTest
    static void getTerritoryInfo4(){

        delete [SELECT Id FROM FormaDistribuicao__c];

        Lead ld = [SELECT Id FROM Lead LIMIT 1];

        Test.startTest();
        Map <String, Object> response = ScheduleCampaignController.getTerritoryInfo(ld.Id, true, new List<String>());
        Test.stopTest();

    }

    @isTest
    static void getTerritoryInfoRisco(){

        Lead ld = [SELECT Id FROM Lead LIMIT 1];
        ServiceTerritory terr = [SELECT Id FROM ServiceTerritory LIMIT 1];
        

        Test.startTest();
        terr.LocalDificilAcesso__c = true;
        update terr;

        Map <String, Object> response1 = ScheduleCampaignController.getTerritoryInfo(ld.Id, true, new List<String>());

        terr.LocalDificilAcesso__c = false;
        terr.Risco__c = true;
        update terr;

        Map <String, Object> response2 = ScheduleCampaignController.getTerritoryInfo(ld.Id, true, new List<String>());

        terr.LocalDificilAcesso__c = true;
        update terr;

        Map <String, Object> response3 = ScheduleCampaignController.getTerritoryInfo(ld.Id, true, new List<String>());
        Test.stopTest();

    }

    @isTest
    static void getTerritoryInfoTerritoryNotFound(){

        Lead ld = [SELECT Id FROM Lead LIMIT 1];
        ServiceTerritory terr = [SELECT Id FROM ServiceTerritory LIMIT 1];
        delete terr;

        Test.startTest();
        Map <String, Object> response = ScheduleCampaignController.getTerritoryInfo(ld.Id, true, new List<String>());
        Test.stopTest();

    }


    /*
    @isTest
    static void getAvailableResource(){
        List<ServiceResource> srs = [SELECT Id, RelatedRecordId FROM ServiceResource];
        ServiceAppointment appt = [SELECT Id FROM ServiceAppointment LIMIT 1];

        appt.SchedStartTime = System.now().addDays(7);
        appt.SchedEndTime = System.now().addDays(8);
        appt.Status = 'Scheduled';
        update appt;

        Test.startTest();
        ServiceResource sr = ScheduleCampaignController.getAvailableResource(srs);
        Test.stopTest();
    }
*/


    @isTest
    static void getNotAvailableDate(){
        ServiceResource sr = [SELECT Id FROM ServiceResource WHERE Name = 'User1' LIMIT 1];
        ServiceTerritory st = [SELECT Id FROM ServiceTerritory LIMIT 1];

        DateTime td = Datetime.now().addDays(7);
        DateTime compareInitDate = DateTime.newInstance(td.year(), td.month(), td.day(), 0, 0, 0);

        ResourceAbsence sa = new ResourceAbsence(
            ResourceId = sr.Id,
            Start = compareInitDate,
            End = compareInitDate.addDays(1),
            Type = 'Almoço'
        );

        Test.startTest();
        List<String> listString1 = ScheduleCampaignController.getNotAvailableDate(sr.Id, td.date(), st.Id);
        insert sa;
        List<String> listString2 = ScheduleCampaignController.getNotAvailableDate(sr.Id, td.date(), st.Id);
        Test.stopTest();
    }

    @isTest
    static void saveSchedule(){
        Lead ld = [SELECT Id FROM Lead LIMIT 1];
        ServiceResource sr = [SELECT Id FROM ServiceResource WHERE Name = 'User1' LIMIT 1];
        ServiceTerritory st = [SELECT Id FROM ServiceTerritory LIMIT 1];

        Test.startTest();
        Map<String, Object> response = ScheduleCampaignController.saveSchedule(ld.Id, sr.Id, st.Id, Date.today().addDays(10), 15, 0, 'description', 'ALINE QUARESMA DA SILVA', false, 'historico');
        Test.stopTest();
    }

    @isTest
    static void getRescheduleoptions(){
        Test.startTest();
        Map<String, String> response = ScheduleCampaignController.getRescheduleoptions();
        Test.stopTest();
    }

    @isTest
    static void reSaveSchedule(){
        Lead ld = [SELECT Id FROM Lead LIMIT 1];
        ServiceResource sr = [SELECT Id FROM ServiceResource WHERE Name = 'User1' LIMIT 1];
        ServiceTerritory st = [SELECT Id FROM ServiceTerritory LIMIT 1];
        ServiceAppointment sa = [SELECT Id FROM ServiceAppointment LIMIT 1];

        sa.SchedStartTime = System.now().addDays(7);
        sa.SchedEndTime = System.now().addDays(8);
        sa.Status = 'Scheduled';
        update sa;

        Test.startTest();
        Map<String, Object> response = ScheduleCampaignController.reSaveSchedule(ld.Id, sr.Id, st.Id, Date.today().addDays(10), 15, 0, 'description', sa.Id, 'Cliente Ausente');
        Test.stopTest();

    }

    @isTest
    static void cancelSchedule(){

        ServiceAppointment sa = [SELECT Id FROM ServiceAppointment LIMIT 1];

        sa.SchedStartTime = System.now().addDays(7);
        sa.SchedEndTime = System.now().addDays(8);
        sa.Status = 'Scheduled';
        update sa;

        Test.startTest();
        ScheduleCampaignController.cancelSchedule(sa.Id, 'Cliente ausente', null);
        Test.stopTest();

    }

    @isTest
    static void getPermissionAgendamentoSabado(){
        Test.startTest();
        ScheduleCampaignController.getPermissionAgendamentoSabado();
        Test.stopTest();
    }

    @isTest
    static void getNotAvailableTime(){
        ServiceResource sr = [SELECT Id FROM ServiceResource LIMIT 1];


        Test.startTest();
        ScheduleCampaignController.getNotAvailableTime(Date.today(), sr.Id);
        Test.stopTest();
    }
}