force-app/main/default/objects/DistribuicaoVisita__c/DistribuicaoVisita__c.object-meta.xml
<CustomObject>
    <label>Distribuição de visita</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribuições de visita</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DistribuicaoVisita__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DistribuicaoVisita__c/fields/NumeroVidas__c.field-meta.xml
<CustomField>
    <fullName>NumeroVidas__c</fullName>
    <label>Número de Vidas</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DistribuicaoVisita__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo de equipe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Call center</fullName>
            </value>
            <value>
                <fullName>Consultores</fullName>
            </value>
            <value>
                <fullName>Equipe corporativa</fullName>
            </value>
            <value>
                <fullName>Loja autorizada</fullName>
            </value>
            <value>
                <fullName>Loja própria</fullName>
            </value>
            <value>
                <fullName>Promotores</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MembroDistribuicaoVisita__c/MembroDistribuicaoVisita__c.object-meta.xml
<CustomObject>
    <label>Membro da distribuição de visita</label>
    <nameField>
        <displayFormat>MDV-{000000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membros da distribuição de visita</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MembroDistribuicaoVisita__c/fields/DistribuicaoVisita__c.field-meta.xml
<CustomField>
    <fullName>DistribuicaoVisita__c</fullName>
    <label>Distribuição de Visita</label>
    <referenceTo>DistribuicaoVisita__c</referenceTo>
    <relationshipLabel>Membros</relationshipLabel>
    <relationshipName>Membros_da_distribuicao_de_visita</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembroDistribuicaoVisita__c/fields/ServiceResource__c.field-meta.xml
<CustomField>
    <fullName>ServiceResource__c</fullName>
    <label>Pessoa</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>ServiceResource.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Membros da distribuição de visita</relationshipLabel>
    <relationshipName>Membros_da_distribuicao_de_visita</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RegionalizacaoDistribuicaoVisita__c/RegionalizacaoDistribuicaoVisita__c.object-meta.xml
<CustomObject>
    <label>Regionalização da distribuição de visita</label>
    <nameField>
        <displayFormat>RDV-{000000}</displayFormat>
        <label>Nome de Regionalização da distribuição d</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regionalizações da distribuição de visit</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RegionalizacaoDistribuicaoVisita__c/fields/DistribuicaoVisita__c.field-meta.xml
<CustomField>
    <fullName>DistribuicaoVisita__c</fullName>
    <label>Distribuição de visita</label>
    <referenceTo>DistribuicaoVisita__c</referenceTo>
    <relationshipLabel>Regionalizações</relationshipLabel>
    <relationshipName>Regionaliza_es_da_distribui_o_de_visit</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RegionalizacaoDistribuicaoVisita__c/fields/ServiceTerritory__c.field-meta.xml
<CustomField>
    <fullName>ServiceTerritory__c</fullName>
    <label>Regionalização</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Distribuição de visita</relationshipLabel>
    <relationshipName>Regionaliza_es_da_distribui_o_de_visit</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <inlineHelpText>Informe se a região é uma Cidade ou Bairro.</inlineHelpText>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cidade</fullName>
            </value>
            <value>
                <fullName>Bairro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/DistribuicaoVisita__c.field-meta.xml
<CustomField>
    <fullName>DistribuicaoVisita__c</fullName>
    <label>Distribuição de visita</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AtribuirRegionalizacaoTest.cls
@isTest
public class AtribuirRegionalizacaoTest {
    

    @TestSetup
    static void setup(){
        ServiceResource rsc = new ServiceResource(
            IsActive = true,
            RelatedRecordId = UserInfo.getUserId(),
            Name = 'User',
            ResourceType = 'T'
        );
        insert rsc;

        DistribuicaoVisita__c dist = new DistribuicaoVisita__c(
            Tipo__c = 'Call center',
            NumeroVidas__c = 1,
            Codigo__c = 'PME1',
            Name = 'PME1'
        );
        insert dist;

        MembroDistribuicaoVisita__c membro1 = new MembroDistribuicaoVisita__c();
        membro1.ServiceResource__c = rsc.Id;
        membro1.DistribuicaoVisita__c = dist.Id;
        insert membro1;

        OperatingHours oh = new OperatingHours(
            Name = 'MyOpHours'
        );
        insert oh;

        createTimeSlots(oh.Id);

        ServiceTerritory terr = new ServiceTerritory(
            Name = 'Centro',
            OperatingHoursId = oh.Id,
            IsActive = true
        );
        insert terr;

        RegionalizacaoDistribuicaoVisita__c rdv = new RegionalizacaoDistribuicaoVisita__c(
            ServiceTerritory__c = terr.Id,
            DistribuicaoVisita__c = dist.Id
        );
        insert rdv;
        
    }

    static void createTimeSlots(Id OperatingHoursId){

        List<String> days = new List<String>{'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'};

        List<TimeSlot> tss = new List<TimeSlot>();

        for(String day : days){
            TimeSlot ts = new TimeSlot(
                OperatingHoursId = OperatingHoursId,
                DayOfWeek = day,
                StartTime = Time.newInstance(0, 0, 0, 0),
                EndTime = Time.newInstance(23, 59, 59, 0)   
            );
            
            tss.add(ts);
        }
        
        insert tss;
    }

    @isTest
    static void atribuirTest(){

        DistribuicaoVisita__c dv = [SELECT Id FROM DistribuicaoVisita__c LIMIT 1];

        Test.startTest();
        AtribuirRegionalizacao.atribuir(new Set<Id>{dv.Id});
        Test.stopTest();
    }
}