force-app/main/default/objects/DistribuicaoVisita__c/DistribuicaoVisita__c.object-meta.xml
<CustomObject>
    <label>Distribuição de visita</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribuições de visita</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DistribuicaoVisita__c/fields/NumeroVidas__c.field-meta.xml
<CustomField>
    <fullName>NumeroVidas__c</fullName>
    <label>Número de Vidas</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DistribuicaoVisita__c/fields/PessoaFisica__c.field-meta.xml
<CustomField>
    <fullName>PessoaFisica__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Atende os Leads dos tipos:
Pessoa Física;
Pessoa Física RN; 
Médico cooperado;</inlineHelpText>
    <label>Pessoa Fisica</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DistribuicaoVisita__c/fields/PessoaJuridica__c.field-meta.xml
<CustomField>
    <fullName>PessoaJuridica__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Atende os Leads Pessoa Jurídica conforme faixa de números de vidas que atende os portes:
PME2;
ME;
GC;
CE;</inlineHelpText>
    <label>Pessoa Jurídica</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MembroDistribuicaoVisita__c/MembroDistribuicaoVisita__c.object-meta.xml
<CustomObject>
    <label>Membro da distribuição de visita</label>
    <nameField>
        <displayFormat>MDV-{000000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membros da distribuição de visita</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MembroDistribuicaoVisita__c/fields/DistribuicaoVisita__c.field-meta.xml
<CustomField>
    <fullName>DistribuicaoVisita__c</fullName>
    <label>Distribuição de Visita</label>
    <referenceTo>DistribuicaoVisita__c</referenceTo>
    <relationshipLabel>Membros</relationshipLabel>
    <relationshipName>Membros_da_distribuicao_de_visita</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembroDistribuicaoVisita__c/fields/ServiceResource__c.field-meta.xml
<CustomField>
    <fullName>ServiceResource__c</fullName>
    <label>Pessoa</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>ServiceResource.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Membros da distribuição de visita</relationshipLabel>
    <relationshipName>Membros_da_distribuicao_de_visita</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/DistribuicaoVisita__c.field-meta.xml
<CustomField>
    <fullName>DistribuicaoVisita__c</fullName>
    <label>Distribuição de visita</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ServiceResourceChooseTest.cls
@isTest
public class ServiceResourceChooseTest {
    
    @testSetup
    static void setup(){

        ServiceResource rsc = new ServiceResource(
            IsActive = true,
            RelatedRecordId = UserInfo.getUserId(),
            Name = 'User1',
            ResourceType = 'T'
        );
        insert rsc;

        DistribuicaoVisita__c dv = new DistribuicaoVisita__c(
            PessoaFisica__c = true,
            PessoaJuridica__c = true,
            Name = 'Primeira Distribuicao',
            NumeroVidas__c = 31
        );
        insert dv;

        MembroDistribuicaoVisita__c mdv = new MembroDistribuicaoVisita__c(
            ServiceResource__c = rsc.Id,
            DistribuicaoVisita__c = dv.Id
        );
        insert mdv;

        createUser();
    }

    static void createUser(){
        Profile p = [SELECT Id FROM Profile WHERE Name LIKE '%Admin%' LIMIT 1]; 
    	User u = new User(
            Alias = 'standt', 
            Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', 
            LastName='Testing', 
            LanguageLocaleKey='en_US',        
            LocaleSidKey='en_US', 
            ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', 
            UserName='testusertest@testorgtest.com'
        );
        insert u;

    	User u2 = new User(
            Alias = 'standt2', 
            Email='standarduser2@testorg.com', 
            EmailEncodingKey='UTF-8', 
            LastName='Testing2', 
            LanguageLocaleKey='en_US',        
            LocaleSidKey='en_US', 
            ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', 
            UserName='testusertest2@testorgtest.com'
        );
        insert u2;

        ServiceResource rsc = new ServiceResource(
            IsActive = true,
            RelatedRecordId = u2.Id,
            Name = 'User2',
            ResourceType = 'T'
        );
        insert rsc;

    }

    @isTest
    static void testGetRespurce(){
        List<ServiceResource> srs = [SELECT Id FROM ServiceResource];

        List<ServiceResourceChoose> srcs = new List<ServiceResourceChoose>();

        for(ServiceResource sr : srs){
            ServiceResourceChoose src = new ServiceResourceChoose();
            src.resourceId = sr.Id;
            src.quant = 2;

            srcs.add(src);
        }

        Test.startTest();
        List<ServiceResourceChoose> response = ServiceResourceChoose.compareServicesResources(srcs);
        Test.stopTest();
   }

}