force-app/main/default/objects/DistribuicaoVisita__c/DistribuicaoVisita__c.object-meta.xml
<CustomObject>
    <label>Distribuição de visita</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribuições de visita</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RegionalizacaoDistribuicaoVisita__c/RegionalizacaoDistribuicaoVisita__c.object-meta.xml
<CustomObject>
    <label>Regionalização da distribuição de visita</label>
    <nameField>
        <displayFormat>RDV-{000000}</displayFormat>
        <label>Nome de Regionalização da distribuição d</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regionalizações da distribuição de visit</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RegionalizacaoDistribuicaoVisita__c/fields/DistribuicaoVisita__c.field-meta.xml
<CustomField>
    <fullName>DistribuicaoVisita__c</fullName>
    <label>Distribuição de visita</label>
    <referenceTo>DistribuicaoVisita__c</referenceTo>
    <relationshipLabel>Regionalizações</relationshipLabel>
    <relationshipName>Regionaliza_es_da_distribui_o_de_visit</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RegionalizacaoDistribuicaoVisitaDomain.cls
public without sharing class RegionalizacaoDistribuicaoVisitaDomain {
    
    private static RegionalizacaoDistribuicaoVisitaDomain instance = null;
    
    public static RegionalizacaoDistribuicaoVisitaDomain getInstance() {
        if (instance == null) {
            instance = new RegionalizacaoDistribuicaoVisitaDomain();
        }
        
        return instance;
    }

    public void atribuir(List<RegionalizacaoDistribuicaoVisita__c> rdvs){
        Set<Id> dvIds = new Set<Id>();

        for(RegionalizacaoDistribuicaoVisita__c rdv : rdvs){
            dvIds.add(rdv.DistribuicaoVisita__c);
        }

        AtribuirRegionalizacao.atribuir(dvIds);
    }

}