force-app/main/default/objects/DistribuicaoVisita__c/DistribuicaoVisita__c.object-meta.xml
<CustomObject>
    <label>Distribuição de visita</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribuições de visita</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MembroDistribuicaoVisita__c/MembroDistribuicaoVisita__c.object-meta.xml
<CustomObject>
    <label>Membro da distribuição de visita</label>
    <nameField>
        <displayFormat>MDV-{000000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membros da distribuição de visita</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MembroDistribuicaoVisita__c/fields/DistribuicaoVisita__c.field-meta.xml
<CustomField>
    <fullName>DistribuicaoVisita__c</fullName>
    <label>Distribuição de Visita</label>
    <referenceTo>DistribuicaoVisita__c</referenceTo>
    <relationshipLabel>Membros</relationshipLabel>
    <relationshipName>Membros_da_distribuicao_de_visita</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembroDistribuicaoVisita__c/fields/ServiceResource__c.field-meta.xml
<CustomField>
    <fullName>ServiceResource__c</fullName>
    <label>Pessoa</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>ServiceResource.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Membros da distribuição de visita</relationshipLabel>
    <relationshipName>Membros_da_distribuicao_de_visita</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RegionalizacaoDistribuicaoVisita__c/RegionalizacaoDistribuicaoVisita__c.object-meta.xml
<CustomObject>
    <label>Regionalização da distribuição de visita</label>
    <nameField>
        <displayFormat>RDV-{000000}</displayFormat>
        <label>Nome de Regionalização da distribuição d</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regionalizações da distribuição de visit</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RegionalizacaoDistribuicaoVisita__c/fields/DistribuicaoVisita__c.field-meta.xml
<CustomField>
    <fullName>DistribuicaoVisita__c</fullName>
    <label>Distribuição de visita</label>
    <referenceTo>DistribuicaoVisita__c</referenceTo>
    <relationshipLabel>Regionalizações</relationshipLabel>
    <relationshipName>Regionaliza_es_da_distribui_o_de_visit</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RegionalizacaoDistribuicaoVisita__c/fields/ServiceTerritory__c.field-meta.xml
<CustomField>
    <fullName>ServiceTerritory__c</fullName>
    <label>Regionalização</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Distribuição de visita</relationshipLabel>
    <relationshipName>Regionaliza_es_da_distribui_o_de_visit</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AtribuirRegionalizacao.cls
public without sharing class AtribuirRegionalizacao {
    
    @future
    static public void atribuir(Set<Id> dvIds){

        List<RegionalizacaoDistribuicaoVisita__c> rdvs = [SELECT Id, DistribuicaoVisita__c, ServiceTerritory__c FROM RegionalizacaoDistribuicaoVisita__c WHERE DistribuicaoVisita__c IN :dvIds];
        List<MembroDistribuicaoVisita__c> mdvs = [SELECT Id, DistribuicaoVisita__c, ServiceResource__c FROM MembroDistribuicaoVisita__c WHERE DistribuicaoVisita__c IN : dvIds];

        Map<Id, Set<Id>> mapDvSt = new Map<Id, Set<Id>>();
        for(RegionalizacaoDistribuicaoVisita__c rdv : rdvs){
            if(!mapDvSt.containsKey(rdv.DistribuicaoVisita__c)){
                mapDvSt.put(rdv.DistribuicaoVisita__c, new Set<Id>());
            }

            mapDvSt.get(rdv.DistribuicaoVisita__c).add(rdv.ServiceTerritory__c);
        }

        Map<Id, Boolean> mapSrP = new Map<Id, Boolean>();
        Map<Id, Set<Id>> mapDvSr = new Map<Id, Set<Id>>();
        for(MembroDistribuicaoVisita__c mdv : mdvs){
            if(!mapDvSr.containsKey(mdv.DistribuicaoVisita__c)){
                mapDvSr.put(mdv.DistribuicaoVisita__c, new Set<Id>());
            }

            mapDvSr.get(mdv.DistribuicaoVisita__c).add(mdv.ServiceResource__c);
            mapSrP.put(mdv.ServiceResource__c, false);
        }

        List<ServiceTerritoryMember> stms = [SELECT Id, ServiceResourceId FROM ServiceTerritoryMember WHERE ServiceResourceId IN :mapSrP.keySet() AND TerritoryType = 'P'];

        for(ServiceTerritoryMember stm : stms){
            mapSrP.put(stm.ServiceResourceId, true);
        }


        List<ServiceTerritoryMember> mterrs = new List<ServiceTerritoryMember>();
        for(Id dvId : mapDvSt.keySet()){
            for(Id stId : mapDvSt.get(dvId)){
                if(mapDvSr.containsKey(dvId)){
                    for(Id srId : mapDvSr.get(dvId)){

                        ServiceTerritoryMember mterr = new ServiceTerritoryMember(
                            ServiceResourceId = srId,
                            ServiceTerritoryId = stId,
                            EffectiveStartDate = System.now(),
                            TerritoryType = mapSrP.get(srId) ? 'S' : 'P'
                        );

                        mterrs.add(mterr);

                        mapSrP.put(srId, true);
                    }
                }
            }
        }

        List<Database.SaveResult> results = Database.insert(mterrs, false);
        System.debug(results);
    }
}