force-app/main/default/objects/AgendamentoDistribuicao__mdt/AgendamentoDistribuicao__mdt.object-meta.xml
<CustomObject>
    <description>Metadado utilizado para gerenciar o processo de distribuição dos leads. Possui os campos quantidade atual, que reflete a quantidade de leads que já foram direcionados a um tipo de carteira, e quantidade máxima, que é o limite definido para mudança do destinatário dos leads.</description>
    <label>Agendamento de Distribuição</label>
    <pluralLabel>Agendamentos de Distribuição</pluralLabel>
</CustomObject>

force-app/main/default/objects/AgendamentoDistribuicao__mdt/fields/QuantidadeAtual__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeAtual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade atual</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CustomMetadataCallbackTest.cls
@isTest
private class CustomMetadataCallbackTest {

    @isTest static void handleResult() {
        CustomMetadataCallback customMetadataCallback = new CustomMetadataCallback();

        Metadata.DeployResult result = new Metadata.DeployResult();
        result.status = Metadata.DeployStatus.Succeeded;

        Metadata.DeployResult result2 = new Metadata.DeployResult();
        result2.status = Metadata.DeployStatus.Failed;

        Test.startTest();
        customMetadataCallback.handleResult(result, null);
        customMetadataCallback.handleResult(result2, null);
        Test.stopTest();
    }

    @isTest static void createUpdateMetadata(){
        Test.startTest();
        CustomMetadataCallback.createUpdateMetadata('AgendamentoDistribuicao__mdt.LojaAutorizada', 'Loja autorizada', 'QuantidadeAtual__c', 0); 
        Test.stopTest();
    }
}