force-app/main/default/objects/AgendamentoDistribuicao__mdt/AgendamentoDistribuicao__mdt.object-meta.xml
<CustomObject>
    <description>Metadado utilizado para gerenciar o processo de distribuição dos leads. Possui os campos quantidade atual, que reflete a quantidade de leads que já foram direcionados a um tipo de carteira, e quantidade máxima, que é o limite definido para mudança do destinatário dos leads.</description>
    <label>Agendamento de Distribuição</label>
    <pluralLabel>Agendamentos de Distribuição</pluralLabel>
</CustomObject>

force-app/main/default/objects/AgendamentoDistribuicao__mdt/fields/QuantidadeAtual__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeAtual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade atual</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgendamentoDistribuicao__mdt/fields/QuantidadePermitida__c.field-meta.xml
<CustomField>
    <fullName>QuantidadePermitida__c</fullName>
    <label>Quantidade permitida</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PeriodoCompetencia__mdt/PeriodoCompetencia__mdt.object-meta.xml
<CustomObject>
    <description>Metadado que guarda informações da data da úlitma ata gerada para um determinado Lead.</description>
    <label>Período de competência</label>
    <pluralLabel>Períodos de competência</pluralLabel>
</CustomObject>

force-app/main/default/objects/PeriodoCompetencia__mdt/fields/DataUltimaCompetencia__c.field-meta.xml
<CustomField>
    <fullName>DataUltimaCompetencia__c</fullName>
    <label>Data da última da competência</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PeriodoCompetencia__mdt/fields/DiasSucessores__c.field-meta.xml
<CustomField>
    <fullName>DiasSucessores__c</fullName>
    <label>Dias sucessores</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ScheduleCampaignControllerFactory.cls
@isTest
public class ScheduleCampaignControllerFactory {
        
    public static AgendamentoDistribuicao__mdt createMeta(){
        AgendamentoDistribuicao__mdt ad = new AgendamentoDistribuicao__mdt();
        ad.QuantidadeAtual__c = 10;
        ad.QuantidadePermitida__c = 10;
        ad.Label = 'Loja autorizada';
        return ad;
    }
    
    public static PeriodoCompetencia__mdt createMetaPeriodo(){
        PeriodoCompetencia__mdt pc = new PeriodoCompetencia__mdt();
        pc.DataUltimaCompetencia__c = Date.today();
        pc.DiasSucessores__c = 2;
        pc.Label = 'Periodo Teste';
        return pc;
    }
}