force-app/main/default/objects/Corretora__c/Corretora__c.object-meta.xml
<CustomObject>
    <label>Corretora</label>
    <nameField>
        <label>Nome da Corretora</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corretoras</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Corretora__c/fields/CelularContato__c.field-meta.xml
<CustomField>
    <fullName>CelularContato__c</fullName>
    <label>Celular do Contato</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <inlineHelpText>Escreva só números, sem traços ou pontos.</inlineHelpText>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/DataDeAberturaDaCorretora__c.field-meta.xml
<CustomField>
    <fullName>DataDeAberturaDaCorretora__c</fullName>
    <label>Data de Abertura da Corretora</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/DiaAniversarioCorretora__c.field-meta.xml
<CustomField>
    <fullName>DiaAniversarioCorretora__c</fullName>
    <formula>TEXT(DAY(DataDeAberturaDaCorretora__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dia do aniversário corretora</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/DiasFaltantesAniversario__c.field-meta.xml
<CustomField>
    <fullName>DiasFaltantesAniversario__c</fullName>
    <formula>ProximoAniversarioCorretora__c - Today()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dias faltantes para o aniversário</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/EmailContato__c.field-meta.xml
<CustomField>
    <fullName>EmailContato__c</fullName>
    <label>Email do Contato</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/Endereco__c.field-meta.xml
<CustomField>
    <fullName>Endereco__c</fullName>
    <label>Endereço</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/EnderecoBairro__c.field-meta.xml
<CustomField>
    <fullName>EnderecoBairro__c</fullName>
    <label>Bairro</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/EnderecoCep__c.field-meta.xml
<CustomField>
    <fullName>EnderecoCep__c</fullName>
    <label>CEP</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/EnderecoCidade__c.field-meta.xml
<CustomField>
    <fullName>EnderecoCidade__c</fullName>
    <label>Cidade</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/EnderecoComplemento__c.field-meta.xml
<CustomField>
    <fullName>EnderecoComplemento__c</fullName>
    <label>Complemento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/EnderecoEstado__c.field-meta.xml
<CustomField>
    <fullName>EnderecoEstado__c</fullName>
    <label>Estado</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/EnderecoLocalizacao__c.field-meta.xml
<CustomField>
    <fullName>EnderecoLocalizacao__c</fullName>
    <label>Localizaçao</label>
    <scale>13</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/EnderecoNumero__c.field-meta.xml
<CustomField>
    <fullName>EnderecoNumero__c</fullName>
    <label>Número</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/EnderecoPais__c.field-meta.xml
<CustomField>
    <fullName>EnderecoPais__c</fullName>
    <label>País</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/EnderecoRua__c.field-meta.xml
<CustomField>
    <fullName>EnderecoRua__c</fullName>
    <label>Rua</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/MesAniversarioCorretora__c.field-meta.xml
<CustomField>
    <fullName>MesAniversarioCorretora__c</fullName>
    <formula>TEXT(MONTH(DataDeAberturaDaCorretora__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mês do aniversário corretora</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/NomeContato__c.field-meta.xml
<CustomField>
    <fullName>NomeContato__c</fullName>
    <label>Primeiro Nome do Contato</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/ProximoAniversarioCorretora__c.field-meta.xml
<CustomField>
    <fullName>ProximoAniversarioCorretora__c</fullName>
    <formula>DATE(IF(TODAY()&lt;date(year(today()),month(DataDeAberturaDaCorretora__c),DAY(DataDeAberturaDaCorretora__c)),YEAR(TODAY()),YEAR(TODAY())+1),month(DataDeAberturaDaCorretora__c),
DAY(DataDeAberturaDaCorretora__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Próximo aniversário da Corretora</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/SobrenomeContato__c.field-meta.xml
<CustomField>
    <fullName>SobrenomeContato__c</fullName>
    <label>Sobrenome Contato</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/TelefoneContato__c.field-meta.xml
<CustomField>
    <fullName>TelefoneContato__c</fullName>
    <label>Telefone do Contato</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/CorretoraDAO.cls
public with sharing class CorretoraDAO {
    public static Corretora__c getById(Id id) {
        Corretora__c corretora = [SELECT Id, 
        CelularContato__c, 
        CNPJ__c,
        DataDeAberturaDaCorretora__c,
        DiaAniversarioCorretora__c,
        DiasFaltantesAniversario__c,
        EmailContato__c,
        Endereco__c,
        EnderecoBairro__c,
        EnderecoCep__c,
        EnderecoCidade__c,
        EnderecoComplemento__c,
        EnderecoEstado__c,
        EnderecoLocalizacao__c,
        EnderecoNumero__c,
        EnderecoPais__c,
        EnderecoRua__c,
        MesAniversarioCorretora__c,
        Name,
        NomeContato__c,
        OwnerId,
        ProximoAniversarioCorretora__c,
        SobrenomeContato__c,
        TelefoneContato__c
        FROM Corretora__c WHERE Id =:id];

        return corretora;
    }
}