force-app/main/default/objects/Corretora__c/Corretora__c.object-meta.xml
<CustomObject>
    <label>Corretora</label>
    <nameField>
        <label>Nome da Corretora</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corretoras</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Corretora__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <inlineHelpText>Escreva só números, sem traços ou pontos.</inlineHelpText>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/DataDeAberturaDaCorretora__c.field-meta.xml
<CustomField>
    <fullName>DataDeAberturaDaCorretora__c</fullName>
    <label>Data de Abertura da Corretora</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/Endereco__c.field-meta.xml
<CustomField>
    <fullName>Endereco__c</fullName>
    <label>Endereço</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/EnderecoBairro__c.field-meta.xml
<CustomField>
    <fullName>EnderecoBairro__c</fullName>
    <label>Bairro</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/EnderecoCidade__c.field-meta.xml
<CustomField>
    <fullName>EnderecoCidade__c</fullName>
    <label>Cidade</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/SobrenomeContato__c.field-meta.xml
<CustomField>
    <fullName>SobrenomeContato__c</fullName>
    <label>Sobrenome Contato</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Corretora__c/fields/TelefoneContato__c.field-meta.xml
<CustomField>
    <fullName>TelefoneContato__c</fullName>
    <label>Telefone do Contato</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Corretora__c.field-meta.xml
<CustomField>
    <fullName>Corretora__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corretora</label>
    <referenceTo>Corretora__c</referenceTo>
    <relationshipLabel>Visitas</relationshipLabel>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/ServiceResource__c.field-meta.xml
<CustomField>
    <fullName>ServiceResource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurso de serviço</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Compromissos de serviços</relationshipLabel>
    <relationshipName>Compromissos_de_servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Corretora__c.field-meta.xml
<CustomField>
    <fullName>Corretora__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corretora</label>
    <referenceTo>Corretora__c</referenceTo>
    <relationshipLabel>Agendamentos</relationshipLabel>
    <relationshipName>Agendamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/EmailsInteressados__c.field-meta.xml
<CustomField>
    <fullName>EmailsInteressados__c</fullName>
    <label>Emails Interessados</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/gestaoAgendamentosControllerTest.cls
@isTest
public class gestaoAgendamentosControllerTest {
    @testSetup
    static void setup() {
        Corretora__c co = new Corretora__c(
            Name = 'Corretora Teste',
            CNPJ__c = '12345678900000',
            DataDeAberturaDaCorretora__c = date.today(),
            TelefoneContato__c = '111111111',
            SobrenomeContato__c = 'Teste',
            Endereco__c = 'Teste', 
            EnderecoCidade__c = 'Belo Horizonte',
            EnderecoBairro__c = 'Goiânia'
        );
        insert co;
        
       Corretora__c co2 = new Corretora__c(
            Name = 'Corretora Teste2',
            CNPJ__c = '12345678900001',
            DataDeAberturaDaCorretora__c = date.today(),
            TelefoneContato__c = '111121111',
            SobrenomeContato__c = 'Teste',
            Endereco__c = 'Teste',
            EnderecoCidade__c = 'Belo Horizonte',
            EnderecoBairro__c = 'Goiânia'
        );
        insert co2;
        
        ServiceResource rsc = new ServiceResource(
            IsActive = true,
            RelatedRecordId = UserInfo.getUserId(),
            Name = 'User1',
            ResourceType = 'T'
        );
        insert rsc;
        
        WorkOrder wo = new WorkOrder(
            Status = 'New',
            Corretora__c = co.Id,
            EmailsInteressados__c = 'emailtest@email.com.br.test'
        );
        insert wo;
        
        ServiceAppointment appt = new ServiceAppointment(
            ParentRecordId = wo.Id,
            Corretora__c = co.Id,
            Status = 'Scheduled',
            EarliestStartTime = System.now().addDays(7).addHours(-4),
            DueDate = System.now().addDays(8),
            ActualStartTime = System.now().addDays(7),
            ServiceResource__c = rsc.Id
        );
        insert appt;
        
        ServiceAppointment appt2 = new ServiceAppointment(
            ParentRecordId = wo.Id,
            Status = 'Scheduled',
            EarliestStartTime = System.now().addDays(7),
            DueDate = System.now().addDays(8),
            ActualStartTime = System.now().addDays(7),
            ServiceResource__c = rsc.Id
        );
        insert appt2;
        
        OperatingHours oh = new OperatingHours(
            Name = 'MyOpHours'
        );
        insert oh;
        
        ServiceTerritory terr = new ServiceTerritory(
            Name = 'Belo Horizonte',
            OperatingHoursId = oh.Id,
            IsActive = true
        );
        insert terr;
    }

    @isTest 
    public static void hasAccessTest() {
        String id = [SELECT Id, RelatedRecordId FROM ServiceResource LIMIT 1].RelatedRecordId;

        Test.startTest();
        gestaoAgendamentosController.hasAccess(id);
        Test.stopTest();
    }
    
    @isTest 
    public static void getTerritoryInfoTest() {
        Id co = [SELECT Id FROM Corretora__c LIMIT 1].Id;
        //ServiceResource rsc = [SELECT Id FROM ServiceResource WHERE Name = 'User1' LIMIT 1];
        String id = [SELECT Id, RelatedRecordId FROM ServiceResource LIMIT 1].RelatedRecordId;

        Test.startTest();
        gestaoAgendamentosController.getTerritoryInfo(co,id);
        Test.stopTest();
    }
    
    @isTest 
    public static void getTerritoryInfoTest2() {
        Id co2 = [SELECT Id, Name FROM Corretora__c WHERE Name = 'Corretora Teste2' LIMIT 1].Id;
        String id = [SELECT Id, RelatedRecordId FROM ServiceResource LIMIT 1].RelatedRecordId;

        Test.startTest();
        gestaoAgendamentosController.getTerritoryInfo(co2,id);
        Test.stopTest();
    }
    
    @isTest 
    public static void getAppTest() {
        Id co = [SELECT Id, Name FROM Corretora__c WHERE Name = 'Corretora Teste2' LIMIT 1].Id;
        ServiceResource rsc = [SELECT Id FROM ServiceResource WHERE Name = 'User1' LIMIT 1];
       
        Date scheDate = Date.today().addDays(7);
        String scheTime = '5';
        Id us = UserInfo.getUserId();
        
        Test.startTest();
        gestaoAgendamentosController.getApp(co,us,scheDate,scheTime);
        gestaoAgendamentosController.getAvailableSchedule(scheDate,co,us);
        Test.stopTest();
    }
    
    @isTest 
    public static void CRUDTests() {
        Id co = [SELECT Id, Name FROM Corretora__c WHERE Name = 'Corretora Teste2' LIMIT 1].Id;
        ServiceTerritory st = [SELECT Id FROM ServiceTerritory LIMIT 1];
        ServiceAppointment sa = [SELECT Id, EarliestStartTime FROM ServiceAppointment LIMIT 1];
        
        Id us = UserInfo.getUserId();
        Date scheDate = Date.today().addDays(7);
        String scheTime = '5';
        String mot = 'Cliente ausente';
        String subMot = '';
        
        Test.startTest();
        gestaoAgendamentosController.saveSchedule(co,us,st.Id,scheDate,scheTime,mot);
        gestaoAgendamentosController.saveReschedule(scheDate,scheTime,mot,sa.Id,mot);
        gestaoAgendamentosController.cancelSchedule(sa.Id, mot,subMot);
        Test.stopTest();
    }
}