force-app/main/default/objects/Corretora__c/Corretora__c.object-meta.xml
<CustomObject>
    <label>Corretora</label>
    <nameField>
        <label>Nome da Corretora</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corretoras</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceAppointment/fields/AtendimentoCallCenter__c.field-meta.xml
<CustomField>
    <fullName>AtendimentoCallCenter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Atendimento Call Center</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Corretora__c.field-meta.xml
<CustomField>
    <fullName>Corretora__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corretora</label>
    <referenceTo>Corretora__c</referenceTo>
    <relationshipLabel>Visitas</relationshipLabel>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FormattedDate__c.field-meta.xml
<CustomField>
    <fullName>FormattedDate__c</fullName>
    <formula>SUBSTITUTE(TEXT(TIMEVALUE(EarliestStartTime-(180/1440))), &apos;:00.000&apos;, &apos;&apos;)</formula>
    <label>Formatted Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/ServiceResource__c.field-meta.xml
<CustomField>
    <fullName>ServiceResource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurso de serviço</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Compromissos de serviços</relationshipLabel>
    <relationshipName>Compromissos_de_servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/ServiceTerritory__c.field-meta.xml
<CustomField>
    <fullName>ServiceTerritory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Compromissos de serviços</relationshipLabel>
    <relationshipName>Compromissos_de_servi_os</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ServiceAppointmentDAO.cls
public with sharing class ServiceAppointmentDAO {
    public static List<ServiceAppointment> getByIdAndStatus(Id id, Id resource) {
        List<ServiceAppointment> lst = [SELECT 
        Id, 
        Status, 
        EarliestStartTime, 
        SchedStartTime, 
        ServiceResource__c, 
        ServiceTerritory__c, 
        AtendimentoCallCenter__c 
        FROM ServiceAppointment WHERE Corretora__c =: id AND ServiceResource__c =: resource AND (Status ='Scheduled' OR Status ='In Progress')];

        return lst;
    }

    public static List<ServiceAppointment> getByResource(Id id, Id resource, DateTime dt1, DateTime dt2) {
        List<ServiceAppointment> lst = [SELECT 
        Id, 
        Status, 
        EarliestStartTime, 
        FormattedDate__c,
        AppointmentNumber,
        SchedStartTime, 
        ServiceResource__c, 
        ServiceTerritory__c, 
        AtendimentoCallCenter__c 
        FROM ServiceAppointment WHERE ServiceResource__c =: resource AND (Status ='Scheduled' OR Status ='In Progress') AND  EarliestStartTime >=: dt1 AND  EarliestStartTime <=: dt2];

        return lst;
    }
}