force-app/main/default/objects/Meta__c/Meta__c.object-meta.xml
<CustomObject>
    <label>Meta</label>
    <nameField>
        <displayFormat>MT-{000000}</displayFormat>
        <label>Número de Meta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meta__c/fields/Ano__c.field-meta.xml
<CustomField>
    <fullName>Ano__c</fullName>
    <label>Ano</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meta__c/fields/Competencia__c.field-meta.xml
<CustomField>
    <fullName>Competencia__c</fullName>
    <label>Competência</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Janeiro</fullName>
            </value>
            <value>
                <fullName>Fevereiro</fullName>
            </value>
            <value>
                <fullName>Março</fullName>
            </value>
            <value>
                <fullName>Abril</fullName>
            </value>
            <value>
                <fullName>Maio</fullName>
            </value>
            <value>
                <fullName>Junho</fullName>
            </value>
            <value>
                <fullName>Julho</fullName>
            </value>
            <value>
                <fullName>Agosto</fullName>
            </value>
            <value>
                <fullName>Setembro</fullName>
            </value>
            <value>
                <fullName>Outubro</fullName>
            </value>
            <value>
                <fullName>Novembro</fullName>
            </value>
            <value>
                <fullName>Dezembro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meta__c/fields/IDCoordenador__c.field-meta.xml
<CustomField>
    <fullName>IDCoordenador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>UserID do Coordenador</description>
    <label>ID do Coordenador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MetasIDCoordenador</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Meta__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <formula>TEXT(Ano__c) + TEXT(Competencia__c) + CASESAFEID(Usuario__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Id Externo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Meta__c/fields/IdExternoLoja__c.field-meta.xml
<CustomField>
    <fullName>IdExternoLoja__c</fullName>
    <formula>TEXT(Ano__c) + TEXT(Competencia__c) + LOWER(SUBSTITUTE(Loja__c, &quot; &quot;, &quot;&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Id Externo Loja</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Meta__c/fields/IDGerente__c.field-meta.xml
<CustomField>
    <fullName>IDGerente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>UserId do Gerente</description>
    <label>ID do Gerente</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MetasIDGerente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Meta__c/fields/IDSupervisor__c.field-meta.xml
<CustomField>
    <fullName>IDSupervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>UserId do Supervisor</description>
    <label>ID do Supervisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MetasIDSupervisor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Meta__c/fields/Loja__c.field-meta.xml
<CustomField>
    <fullName>Loja__c</fullName>
    <label>Loja</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Meta__c/fields/MetaDesafio__c.field-meta.xml
<CustomField>
    <fullName>MetaDesafio__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Meta Desafio</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CompetenciaVigencia__c.field-meta.xml
<CustomField>
    <fullName>CompetenciaVigencia__c</fullName>
    <description>A competência de vigência refere-se ao segundo dia do mês até o primeiro dia do mês seguinte.</description>
    <formula>IF(
				Account.DataVigencia__c &gt;= DATE(YEAR(Account.DataVigencia__c),MONTH(Account.DataVigencia__c),02) &amp;&amp; 
				Account.DataVigencia__c &lt;= DATE(YEAR(Account.DataVigencia__c),MONTH(Account.DataVigencia__c)+1,01), 
				DATE(YEAR(Account.DataVigencia__c),MONTH(Account.DataVigencia__c),01),
				/* Se for o primeiro dia do Ano */
				IF(
								Account.DataVigencia__c = DATE(YEAR(Account.DataVigencia__c),01,01), 
								DATE(YEAR(Account.DataVigencia__c)-1, MONTH(Account.DataVigencia__c)+11,01),
								/* Se for o primeiro dia de qualquer mês, exceto janeiro */
								IF(
												Account.DataVigencia__c = DATE(YEAR(Account.DataVigencia__c),MONTH(Account.DataVigencia__c),01),
												DATE(YEAR(Account.DataVigencia__c),MONTH(Account.DataVigencia__c)-1,01),null)
												
									
				)
)
/*
Pseudocódigo
n1 = 02/01/2021 ou 01/01/2021 ou 01/02/2021

n1 &gt;= 02/month/year e n1 &lt;= 01/month+1/year então 01/01/2021, se não,
n1 = 01/01/year então 01/month+11/year-1, se não,
n1 = 01/month/year então 01/month-1/year
*/</formula>
    <label>Competencia de Vigência_N</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IDCoordenador__c.field-meta.xml
<CustomField>
    <fullName>IDCoordenador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Id do Coordenador</description>
    <label>ID do Coordenador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Oportunidades1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IdGerente__c.field-meta.xml
<CustomField>
    <fullName>IdGerente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Registra o Id do Gerente</description>
    <label>Id do Gerente</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Oportunidades2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IDMetaCoordenador__c.field-meta.xml
<CustomField>
    <fullName>IDMetaCoordenador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Busca a informação da meta do coordenador no objeto meta__c, a meta é compatível com o canal e com a competência. Esta meta não é a desafio.</description>
    <label>ID da Meta do Coordenador</label>
    <referenceTo>Meta__c</referenceTo>
    <relationshipLabel>Oportunidades (Meta Coordenador)</relationshipLabel>
    <relationshipName>Oportunidades2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IDMetaCoordenadorDesafio__c.field-meta.xml
<CustomField>
    <fullName>IDMetaCoordenadorDesafio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Busca a informação da meta desafio do coordenador no objeto meta__c, a meta é compatível com o canal e com a competência.</description>
    <label>Id da Meta Desafio do Coordenador</label>
    <referenceTo>Meta__c</referenceTo>
    <relationshipLabel>Oportunidades (Id da Meta Desafio do Coordenador)</relationshipLabel>
    <relationshipName>Oportunidades4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IDMetaGerente__c.field-meta.xml
<CustomField>
    <fullName>IDMetaGerente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Busca a informação da meta do gerente no objeto meta__c, a meta é compatível com a competência. Esta meta não é a desafio.</description>
    <label>ID da Meta do Gerente</label>
    <referenceTo>Meta__c</referenceTo>
    <relationshipLabel>Oportunidades (Meta do gerente)</relationshipLabel>
    <relationshipName>Oportunidades1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IDMetaGerenteDesafio__c.field-meta.xml
<CustomField>
    <fullName>IDMetaGerenteDesafio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Busca a informação da meta desafio do gerente no objeto meta__c, a meta é compatível com o canal e com a competência.</description>
    <label>Id da Meta Desafio do Gerente</label>
    <referenceTo>Meta__c</referenceTo>
    <relationshipLabel>Oportunidades (Id da Meta Desafio do Gerente)</relationshipLabel>
    <relationshipName>Oportunidades6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IDMetaSupervisor__c.field-meta.xml
<CustomField>
    <fullName>IDMetaSupervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Busca a informação da meta do supervisor no objeto meta__c, a meta é compatível com o canal e com a competência.</description>
    <label>ID da Meta do Supervisor</label>
    <referenceTo>Meta__c</referenceTo>
    <relationshipLabel>Oportunidades (ID da Meta do Supervisor)</relationshipLabel>
    <relationshipName>Oportunidades3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IDSupervisor__c.field-meta.xml
<CustomField>
    <fullName>IDSupervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ID do Supervisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LOJA__c.field-meta.xml
<CustomField>
    <fullName>LOJA__c</fullName>
    <formula>Meta__r.Loja__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LOJA</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Meta__c.field-meta.xml
<CustomField>
    <fullName>Meta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meta</label>
    <referenceTo>Meta__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Loja__c.field-meta.xml
<CustomField>
    <fullName>Loja__c</fullName>
    <description>Informa de qual loja o usuário pertence</description>
    <label>Loja</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CANAL__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>Betim</fullName>
            </value>
            <value>
                <fullName>Lagoa Santa</fullName>
            </value>
            <value>
                <fullName>Santa Luzia</fullName>
            </value>
            <value>
                <fullName>Pedro Leopoldo</fullName>
            </value>
            <value>
                <fullName>Santa Barbara</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VinculacaoOpportunityMetaBatch.cls
global class VinculacaoOpportunityMetaBatch implements Database.Batchable<sObject> {

    public static Map<Integer, String> myMap = new Map<Integer, String>{
        1 => 'Janeiro', 
        2 => 'Fevereiro', 
        3 => 'Março',
        4 => 'Abril', 
        5 => 'Maio', 
        6 => 'Junho',
        7 => 'Julho', 
        8 => 'Agosto', 
        9 => 'Setembro',
        10 => 'Outubro', 
        11 => 'Novembro', 
        12 => 'Dezembro'
    };

    // Exceção II
    private static final List<String> lojasExc1 = new List<String>{
        'BETIM',
        'SANTA LUZIA',
        'LAGOA SANTA',
        'PEDRO LEOPOLDO'
    };

    private static final String LOJA_INTERIOR_LOWER_CASE = 'interior';

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(
            [SELECT 
            Id,
            OwnerId,
            Owner.Name,
            CreatedDate,
            CompetenciaVigencia__c,
            Loja__c
            FROM
            Opportunity
            WHERE Meta__c = null AND CompetenciaVigencia__c != null
            ]
        );
    }

    global void execute(Database.BatchableContext BC, List<Opportunity> oppts) {

        Map<Id, String> mapOpptExternal = new Map<Id, String>();

        // Exceção II
        Map<Id, String> mapMovExternalLojaInteriorExc = new Map<Id, String>();

        //CompetenciaVigencia__c
        for(Opportunity oppt : oppts){
            Date onlyDate = oppt.CompetenciaVigencia__c;
            Datetime dt = Datetime.newInstance(onlyDate.year(), onlyDate.month(), onlyDate.day(), 0, 0, 0);
            
            if(oppt.OwnerId.getsObjectType().getDescribe().getName() == 'User'){
                String externalId = dt.format('YYYY') + getMonthBR(dt.month()) + oppt.OwnerId;
                mapOpptExternal.put(oppt.Id, externalId);
            }

            if(String.isNotBlank(oppt.Loja__c) && lojasExc1.contains(oppt.Loja__c)){
                String externalId = dt.format('YYYY') + getMonthBR(dt.month()) + LOJA_INTERIOR_LOWER_CASE;
                mapMovExternalLojaInteriorExc.put(oppt.Id, externalId);
            }
        }


        //System.debug(mapLeadMetaExternal);

        List<Meta__c> metas = [SELECT Id, IdExterno__c, Ano__c, Competencia__c, IDSupervisor__c, IDCoordenador__c, IDGerente__c FROM Meta__c WHERE IdExterno__c IN :mapOpptExternal.values()];

        Map<String, Meta__c> mapMetas = new Map<String, Meta__c>();
        for(Meta__c meta : metas){
            mapMetas.put(meta.IdExterno__c, meta);
        }

        //System.debug(mapMetas);

        List<Opportunity> opptsToUpdate = new List<Opportunity>();
        for(Id opptId : mapOpptExternal.keySet()){
            Opportunity opptToUpdate = new Opportunity(
                Id = opptId,
                Meta__c = mapMetas.get(mapOpptExternal.get(opptId))?.Id,
                IDSupervisor__c = mapMetas.get(mapOpptExternal.get(opptId))?.IDSupervisor__c,
                IDCoordenador__c = mapMetas.get(mapOpptExternal.get(opptId))?.IDCoordenador__c
            );

            opptsToUpdate.add(opptToUpdate);
        }

        TriggerHandler.bypass(OpportunityTriggerHandler.class);
        List<Database.SaveResult> SR = Database.update(opptsToUpdate, false);
        TriggerHandler.clearBypass(OpportunityTriggerHandler.class);


        //Supervisores, Coordenadores e Gerente
        try{
            Map<String, String> mapMetaWithSupervisor = new Map<String, String>();
            Map<String, String> mapMetaWithCoordenador = new Map<String, String>();
            Map<String, String> mapMetaWithGerente = new Map<String, String>();

            Set<String> mapExternals = new Set<String>();
            for(Meta__c meta : mapMetas.values()){
                String IdExternoSupervisor = meta.Ano__c + meta.Competencia__c + meta.IDSupervisor__c;
                String IdExternoCoordenador = meta.Ano__c + meta.Competencia__c + meta.IDCoordenador__c;
                String IdExternoGerente = meta.Ano__c + meta.Competencia__c + meta.IDGerente__c;

                mapMetaWithSupervisor.put(meta.IdExterno__c, IdExternoSupervisor);
                mapMetaWithCoordenador.put(meta.IdExterno__c, IdExternoCoordenador);
                mapMetaWithGerente.put(meta.IdExterno__c, IdExternoGerente);

                mapExternals.add(IdExternoSupervisor);
                mapExternals.add(IdExternoCoordenador);
                mapExternals.add(IdExternoGerente);
            }

            List<Meta__c> metasOthers = [SELECT Id, IdExterno__c, MetaDesafio__c FROM Meta__c WHERE IdExterno__c IN :mapExternals];
            
            Map<String, Meta__c> mapMetasOthers = new Map<String, Meta__c>();
            Map<String, Meta__c> mapMetasOthersDesafio = new Map<String, Meta__c>();
            for(Meta__c meta : metasOthers){
                if(meta.MetaDesafio__c){
                    mapMetasOthersDesafio.put(meta.IdExterno__c, meta);
                }else{
                    mapMetasOthers.put(meta.IdExterno__c, meta);
                }
            }

            opptsToUpdate = new List<Opportunity>();
            for(Id opptId : mapOpptExternal.keySet()){

                String IdExterno = mapMetas.get(mapOpptExternal.get(opptId))?.IdExterno__c;
                String IdExternoSupervisor = mapMetaWithSupervisor.get(IdExterno);
                String IdExternoCoordenador = mapMetaWithCoordenador.get(IdExterno);
                String IdExternoGerente = mapMetaWithGerente.get(IdExterno);

                Opportunity opptToUpdate = new Opportunity();
                opptToUpdate.Id = opptId;

                opptToUpdate.IDMetaSupervisor__c = mapMetasOthers.get(IdExternoSupervisor)?.Id;

                opptToUpdate.IDMetaCoordenador__c = mapMetasOthers.get(IdExternoCoordenador)?.Id;
                opptToUpdate.IDMetaCoordenadorDesafio__c = mapMetasOthersDesafio.get(IdExternoCoordenador)?.Id;

                opptToUpdate.IDMetaGerente__c = mapMetasOthers.get(IdExternoGerente)?.Id;
                opptToUpdate.IDMetaGerenteDesafio__c = mapMetasOthersDesafio.get(IdExternoGerente)?.Id;

                opptsToUpdate.add(opptToUpdate);
            }

            TriggerHandler.bypass(OpportunityTriggerHandler.class);
            List<Database.SaveResult> SR2 = Database.update(opptsToUpdate, false);
            TriggerHandler.clearBypass(OpportunityTriggerHandler.class);
        }catch(Exception e){
            System.debug(e.getMessage());
        }

        // Exceção II
        try{
            List<Meta__c> metasOthers = [SELECT Id, IdExternoLoja__c, MetaDesafio__c, Ano__c, Competencia__c, IDSupervisor__c, IDCoordenador__c, IDGerente__c FROM Meta__c WHERE IdExternoLoja__c IN :mapMovExternalLojaInteriorExc.values()];
        
            Map<String, Meta__c> mapMetasOthers = new Map<String, Meta__c>();
            for(Meta__c meta : metasOthers){
                mapMetasOthers.put(meta.IdExternoLoja__c, meta);
            }
    
            List<Opportunity> opptsToUpdate2 = new List<Opportunity>();
            for(Id opptId : mapMovExternalLojaInteriorExc.keySet()){
                Opportunity opptToUpdate2 = new Opportunity(
                    Id = opptId,
                    IDMetaSupervisor__c = mapMetasOthers.get(mapMovExternalLojaInteriorExc.get(opptId))?.Id
                );
    
                opptsToUpdate2.add(opptToUpdate2);
            }
    
            List<Database.SaveResult> SR2 = Database.update(opptsToUpdate2, false);
        }catch(Exception e){
            System.debug(e.getMessage());
        }
        
    }

    global void finish(Database.BatchableContext BC) {
        
    }

    public static String getMonthBR(Integer numberS){
        return myMap.get(numberS);
    }
}