force-app/main/default/objects/Meta__c/Meta__c.object-meta.xml
<CustomObject>
    <label>Meta</label>
    <nameField>
        <displayFormat>MT-{000000}</displayFormat>
        <label>Número de Meta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meta__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Metas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MetaTriggerHandler.cls
public without sharing class MetaTriggerHandler extends TriggerHandler {
    
    public override void beforeInsert(){
        setUser((List<Meta__c>) Trigger.new);
    }

    public void setUser(List<Meta__c> metas){
        Map<String, List<Meta__c>> mapEmailMeta = new  Map<String, List<Meta__c>>();

        for(Meta__c meta: metas){
            if(meta.Email__c != null){
                if(!mapEmailMeta.containsKey(meta.Email__c)){
                    mapEmailMeta.put(meta.Email__c, new List<Meta__c>());
                }
                mapEmailMeta.get(meta.Email__c).add(meta);
            }
        }

        List<User> users = [SELECT Id, Email FROM User WHERE Email IN : mapEmailMeta.keySet()];

        for(User u : users){
            if(mapEmailMeta.containsKey(u.Email)){
                for(Meta__c meta : mapEmailMeta.get(u.Email)){
                    meta.OwnerId = u.Id;
                    meta.Usuario__c = u.Id;
                }
            }
        }
    }
}