force-app/main/default/objects/Meta__c/Meta__c.object-meta.xml
<CustomObject>
    <label>Meta</label>
    <nameField>
        <displayFormat>MT-{000000}</displayFormat>
        <label>Número de Meta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meta__c/fields/Ano__c.field-meta.xml
<CustomField>
    <fullName>Ano__c</fullName>
    <label>Ano</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meta__c/fields/Competencia__c.field-meta.xml
<CustomField>
    <fullName>Competencia__c</fullName>
    <label>Competência</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Janeiro</fullName>
            </value>
            <value>
                <fullName>Fevereiro</fullName>
            </value>
            <value>
                <fullName>Março</fullName>
            </value>
            <value>
                <fullName>Abril</fullName>
            </value>
            <value>
                <fullName>Maio</fullName>
            </value>
            <value>
                <fullName>Junho</fullName>
            </value>
            <value>
                <fullName>Julho</fullName>
            </value>
            <value>
                <fullName>Agosto</fullName>
            </value>
            <value>
                <fullName>Setembro</fullName>
            </value>
            <value>
                <fullName>Outubro</fullName>
            </value>
            <value>
                <fullName>Novembro</fullName>
            </value>
            <value>
                <fullName>Dezembro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Movimentacao__c/Movimentacao__c.object-meta.xml
<CustomObject>
    <label>Movimentação</label>
    <nameField>
        <displayFormat>MV-{0000000}</displayFormat>
        <label>Movimentação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movimentações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movimentacao__c/fields/CanalComercializador__c.field-meta.xml
<CustomField>
    <fullName>CanalComercializador__c</fullName>
    <label>Nome canal comercializador Cliente</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Movimentacao__c/fields/Competencia__c.field-meta.xml
<CustomField>
    <fullName>Competencia__c</fullName>
    <label>Competencia</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Movimentacao__c/fields/Meta__c.field-meta.xml
<CustomField>
    <fullName>Meta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meta</label>
    <referenceTo>Meta__c</referenceTo>
    <relationshipLabel>Movimentações</relationshipLabel>
    <relationshipName>Movimenta_es</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Movimentacao__c/fields/NomeVendedor__c.field-meta.xml
<CustomField>
    <fullName>NomeVendedor__c</fullName>
    <label>Nome vendedor</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VinculacaoMovimentacaoMetaBatchTest.cls
@isTest
public class VinculacaoMovimentacaoMetaBatchTest {
    

    @testSetup
    static void setup(){
        Profile p = [SELECT Id FROM Profile WHERE Name LIKE '%Admin%' LIMIT 1]; 
    	User u = new User(
            Alias = 'standt', 
            Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', 
            FirstName='Roberto',
            LastName='Oliveira de Cardoso', 
            LanguageLocaleKey='en_US',        
            LocaleSidKey='en_US', 
            ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', 
            UserName='testusertest@testorgtest.com'
        );
        insert u;


        Meta__c meta = new Meta__c(
            Email__c = 'standarduser@testorg.com',
            Ano__c = Datetime.now().format('YYYY'),
            Competencia__c = VinculacaoMovimentacaoMetaBatch.getMonthBR(Datetime.now().month())
        );
        insert meta;


        Movimentacao__c mov = new Movimentacao__c(
            Competencia__c = Date.today(),
            NomeVendedor__c = 'ROBERTO OLIVEIRA DE CARDOSO',
            CanalComercializador__c = 'VENDAS LJ PROPRIA LAGOA SANTA'
        );
        insert mov;

    }

    @isTest
    static void setMovimentacaoTest(){
        Test.startTest();
        Database.executeBatch(new VinculacaoMovimentacaoMetaBatch(), 200);
        Test.stopTest();
    }
}