force-app/main/default/objects/Cotacoes__c/Cotacoes__c.object-meta.xml
<CustomObject>
    <description>Objeto de cotações que relaciona com usuario, corretora e conta</description>
    <label>Cotações</label>
    <nameField>
        <displayFormat>COT - {0}</displayFormat>
        <label>Cotações</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cotacoes__c/fields/VinculoProposta__c.field-meta.xml
<CustomField>
    <fullName>VinculoProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vinculo Proposta</label>
    <referenceTo>DocumentosProposta__c</referenceTo>
    <relationshipLabel>Cotações</relationshipLabel>
    <relationshipName>Cotacoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentosProposta__c/DocumentosProposta__c.object-meta.xml
<CustomObject>
    <label>Documentos da Proposta</label>
    <nameField>
        <displayFormat>Proposta - {0}</displayFormat>
        <label>Nome de Documentos da Proposta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documentos das Propostas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentosProposta__c/fields/Cotacoes__c.field-meta.xml
<CustomField>
    <fullName>Cotacoes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotações</label>
    <referenceTo>Cotacoes__c</referenceTo>
    <relationshipLabel>Documentos das Propostas</relationshipLabel>
    <relationshipName>DocumentosPropostas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentosProposta__c/fields/Dias__c.field-meta.xml
<CustomField>
    <fullName>Dias__c</fullName>
    <label>Dias duração</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DocumentosProposta__c/fields/Tempo_emiss_o_proposta__c.field-meta.xml
<CustomField>
    <fullName>Tempo_emiss_o_proposta__c</fullName>
    <formula>FORMATDURATION( CreatedDate , Cotacoes__r.CreatedDate )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tempo emissão proposta</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TempoMedio.cls
public class TempoMedio {
    
    DocumentosProposta__c proposta = [SELECT id, Tempo_emiss_o_proposta__c, FORMAT(CreatedDate),FORMAT(Cotacoes__r.CreatedDate),Dias__c from DocumentosProposta__c LIMIT 5];
    Cotacoes__c cotacao = [select id,name,format(CreatedDate)from Cotacoes__c LIMIT 5];
	
    DateTime propostadata = Date.valueOf(proposta.CreatedDate); 
    DateTime CotacaoData = Date.valueOf(cotacao.CreatedDate);
    integer Days = Integer.valueOf((CotacaoData.getTime() - propostadata.getTime())/(1000*60*60*24));
    
    
    //somar todos os minutos e dividir pelos dias
    //por exe soma todos os tempo emissão proposta e divide pelo campo tempo emissao proposta
    
}