force-app/main/default/objects/ConfigLogsAcesso__mdt/ConfigLogsAcesso__mdt.object-meta.xml
<CustomObject>
    <label>Configuração Logs de Acesso</label>
    <pluralLabel>Configurações Logs de Acesso</pluralLabel>
</CustomObject>

force-app/main/default/objects/ConfigLogsAcesso__mdt/fields/MesesManterHistorico__c.field-meta.xml
<CustomField>
    <fullName>MesesManterHistorico__c</fullName>
    <label>Meses a Manter Histórico</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ExcluiLogsAcessoSchedulable.cls
global without sharing class ExcluiLogsAcessoSchedulable implements Schedulable {

    global void execute(SchedulableContext ctx) {
        
        Date hoje = System.today();
        ConfigLogsAcesso__mdt config = [SELECT MesesManterHistorico__c FROM ConfigLogsAcesso__mdt LIMIT 1];
        Integer meses = config != null && config.MesesManterHistorico__c != null ? Integer.valueOf(config.MesesManterHistorico__c) : 12;
        meses = -meses;
		Date dataLimite = hoje.addMonths(meses);
        
        ExcluiLogsAcessoBatch elab = new ExcluiLogsAcessoBatch(dataLimite);
        Id batchId = Database.executeBatch(elab);
    }
}