force-app/main/default/objects/Account/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Inserir o CPF sem pontos, traços ou dígitos.</inlineHelpText>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DataVigencia__c.field-meta.xml
<CustomField>
    <fullName>DataVigencia__c</fullName>
    <label>Data de vigência</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Meta__c/Meta__c.object-meta.xml
<CustomObject>
    <label>Meta</label>
    <nameField>
        <displayFormat>MT-{000000}</displayFormat>
        <label>Número de Meta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meta__c/fields/Ano__c.field-meta.xml
<CustomField>
    <fullName>Ano__c</fullName>
    <label>Ano</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meta__c/fields/Competencia__c.field-meta.xml
<CustomField>
    <fullName>Competencia__c</fullName>
    <label>Competência</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Janeiro</fullName>
            </value>
            <value>
                <fullName>Fevereiro</fullName>
            </value>
            <value>
                <fullName>Março</fullName>
            </value>
            <value>
                <fullName>Abril</fullName>
            </value>
            <value>
                <fullName>Maio</fullName>
            </value>
            <value>
                <fullName>Junho</fullName>
            </value>
            <value>
                <fullName>Julho</fullName>
            </value>
            <value>
                <fullName>Agosto</fullName>
            </value>
            <value>
                <fullName>Setembro</fullName>
            </value>
            <value>
                <fullName>Outubro</fullName>
            </value>
            <value>
                <fullName>Novembro</fullName>
            </value>
            <value>
                <fullName>Dezembro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <externalId>true</externalId>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>E-mail</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Meta__c.field-meta.xml
<CustomField>
    <fullName>Meta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meta</label>
    <referenceTo>Meta__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VinculacaoOpportunityMetaBatchTest.cls
@isTest
public class VinculacaoOpportunityMetaBatchTest {
    
    @testSetup
    static void setup(){
        Profile p = [SELECT Id FROM Profile WHERE Name LIKE '%Admin%' LIMIT 1]; 
    	User u = new User(
            Alias = 'standt', 
            Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', 
            LastName='Testing', 
            LanguageLocaleKey='en_US',        
            LocaleSidKey='en_US', 
            ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', 
            UserName='testusertest@testorgtest.com'
        );
        insert u;

        Account acc = new Account(
            Name = 'New Account',
            DataVigencia__c = Date.today(),
            Phone = '(31) 98888-1717'
        );
        insert acc;

        Opportunity oppt = new Opportunity(
            OwnerId = u.Id,
            Name = 'New Oppt',
            CloseDate = Date.today().addDays(10),
            CPF__c = '111.111.111-10',
            StageName = 'Elaboração de proposta',
            AccountId = acc.Id
        );
        insert oppt;

        Meta__c meta = new Meta__c(
            Email__c = 'standarduser@testorg.com',
            Ano__c = Datetime.now().format('YYYY'),
            Competencia__c = VinculacaoOpportunityMetaBatch.getMonthBR(Datetime.now().month())

        );
        insert meta;
        
    }

    @isTest
    static void setOpportunityTest(){
        Test.startTest();
        Database.executeBatch(new VinculacaoOpportunityMetaBatch(), 200);
        Test.stopTest();
    }
}