force-app/main/default/objects/Lead/fields/AbriuModalAgendamento__c.field-meta.xml
<CustomField>
    <fullName>AbriuModalAgendamento__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Abriu Modal Agendamento</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/HouveAgendamento__c.field-meta.xml
<CustomField>
    <fullName>HouveAgendamento__c</fullName>
    <label>Houve agendamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ModalScheduleComponentController.cls
public without sharing class ModalScheduleComponentController {

    @AuraEnabled
    public static Boolean verificaMostrarModal(String idLead) {

        Boolean mostrar = false;

        Lead ld = [SELECT CreatedDate, HouveAgendamento__c FROM Lead WHERE Id = :idLead];
        
        if (ld.HouveAgendamento__c == 'Sim') {

            Datetime dtCriacao = ld.CreatedDate;
            Datetime agora = System.now();
            Date hoje = agora.date();
            Date dataCriacao = dtCriacao.date();
            Long timeCriacao = dtCriacao.getTime();
            Long timeAgora = agora.getTime();
            Long diffSeg = (timeAgora - timeCriacao)/1000;
            
            if (diffSeg <= 30) {  //simula abrir o modal após criar um registro
                mostrar = true;
            }
        }

        return mostrar;
    }

    @AuraEnabled
    public static void preencheCampoModal(String idLead) {

        Lead lead = new Lead(Id = idLead);
        lead.AbriuModalAgendamento__c = true;
        update lead;
    }
}