force-app/main/default/objects/Lead/fields/Bairro__c.field-meta.xml
<CustomField>
    <fullName>Bairro__c</fullName>
    <label>Bairro</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Numero__c.field-meta.xml
<CustomField>
    <fullName>Numero__c</fullName>
    <label>Número</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/NumeroVidas__c.field-meta.xml
<CustomField>
    <fullName>NumeroVidas__c</fullName>
    <label>Quantidade de Vidas Novas</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Agendamentos</relationshipLabel>
    <relationshipName>Agendamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WorkOrderDomain.cls
public without sharing class WorkOrderDomain {
    
    private static WorkOrderDomain instance = null;
    
    public static WorkOrderDomain getInstance() {
        if (instance == null) {
            instance = new WorkOrderDomain();
        }
        
        return instance;
    }

    public void sendEmailServiceReportFromWOLI(List<WorkOrder> wos, Map<Id, WorkOrder> oldWos){
        List<WorkOrder> woToSend = new List<WorkOrder>();

        Set<Id> leadIds = new Set<Id>();
        for(WorkOrder wo : wos){
            if(wo.Lead__c != null){
                leadIds.add(wo.Lead__c);
            }
        }

        Map<Id, Lead> mapLead = new Map<Id, Lead>([SELECT Id, Email, Street, Numero__c, Bairro__c, City, State, Country, PostalCode, NumeroVidas__c FROM Lead WHERE Id IN :leadIds]);

        for(WorkOrder wo : wos){
            if(wo.Status == 'Completed' && oldWos.get(wo.Id).Status != 'Completed' && 
                wo.Lead__c != null && mapLead.keySet().contains(wo.Lead__c)){
                woToSend.add(wo);
            }
        }

        WorkOrderService.getInstance().sendEmailServiceReportFromWOLI(woToSend, mapLead);
    }

    public void createServiceReportFromWOLI(List<WorkOrder> wos, Map<Id, WorkOrder> oldWos){
        List<WorkOrder> woToSend = new List<WorkOrder>();

        Set<Id> leadIds = new Set<Id>();
        for(WorkOrder wo : wos){
            if(wo.Lead__c != null){
                leadIds.add(wo.Lead__c);
            }
        }

        Map<Id, Lead> mapLead = new Map<Id, Lead>([SELECT Id, Email, Street, Numero__c, Bairro__c, City, State, Country, PostalCode, NumeroVidas__c FROM Lead WHERE Id IN :leadIds]);

        for(WorkOrder wo : wos){
            if(wo.Status == 'Completed' && oldWos.get(wo.Id).Status != 'Completed' && 
                wo.Lead__c != null && mapLead.keySet().contains(wo.Lead__c)){
                woToSend.add(wo);
            }
        }

        WorkOrderService.getInstance().createServiceReportFromWOLI(woToSend);
    }
}