force-app/main/default/objects/Lead/fields/CanalEntrada__c.field-meta.xml
<CustomField>
    <fullName>CanalEntrada__c</fullName>
    <label>Canal de Entrada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Atendimento Loja</fullName>
            </value>
            <value>
                <fullName>Call Center</fullName>
            </value>
            <value>
                <fullName>Blended - AeC</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Promotor</fullName>
            </value>
            <value>
                <fullName>Prospecção</fullName>
            </value>
            <value>
                <fullName>Receptivo - AeC</fullName>
            </value>
            <value>
                <fullName>Consultor</fullName>
            </value>
            <value>
                <fullName>Indicação interna UnimedBH</fullName>
            </value>
            <value>
                <fullName>Indicação</fullName>
            </value>
            <value>
                <fullName>e-Commerce</fullName>
            </value>
            <value>
                <fullName>Hotsite: Soluções Empresa</fullName>
            </value>
            <value>
                <fullName>Ação Araujo</fullName>
            </value>
            <value>
                <fullName>Levantada de mão - Portal</fullName>
            </value>
            <value>
                <fullName>Levantada de mão - Bem Digital</fullName>
            </value>
            <value>
                <fullName>Levantada de mão - Página de Planos</fullName>
            </value>
            <value>
                <fullName>Fala Cliente</fullName>
            </value>
            <value>
                <fullName>RN DE</fullName>
            </value>
            <value>
                <fullName>Base leads Salesforce sem proprietário</fullName>
            </value>
            <value>
                <fullName>Leads Facebook</fullName>
            </value>
            <value>
                <fullName>Mensagens ou comentários Redes Sociais</fullName>
            </value>
            <value>
                <fullName>Ex Cliente Unimed-BH</fullName>
            </value>
            <value>
                <fullName>Nuvidio</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Desconhecido</fullName>
            </value>
            <value>
                <fullName>Levantada de Mão</fullName>
            </value>
            <value>
                <fullName>HubSpot</fullName>
            </value>
            <value>
                <fullName>Páginas ou Campanhas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/ExCliente__c.field-meta.xml
<CustomField>
    <fullName>ExCliente__c</fullName>
    <label>Ex-cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <formula>Latitude</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Latitude</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <formula>Longitude</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Longitude</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Porte__c.field-meta.xml
<CustomField>
    <fullName>Porte__c</fullName>
    <formula>IF(RecordType.Name = &apos;Pessoa Física&apos; || RecordType.Name = &apos;Pessoa Física RN&apos; || RecordType.Name = &apos;Médico Cooperado&apos;,&apos;Individual&apos;,IF(AND(NumeroVidas__c + QtdeVidasTransferencia__c &lt;= 29, RecordType.Name = &apos;Pessoa Jurídica&apos; || RecordType.Name = &apos;Pessoa Jurídica - Enterprise&apos; ), &apos;PME1&apos;,IF(NumeroVidas__c + QtdeVidasTransferencia__c &lt;= 99, &apos;PME2&apos;,IF(NumeroVidas__c + QtdeVidasTransferencia__c &lt;= 300, &apos;ME&apos;,IF(NumeroVidas__c + QtdeVidasTransferencia__c &lt;= 600, &apos;GC&apos;,IF(NumeroVidas__c + QtdeVidasTransferencia__c &gt; 600, &apos;CE&apos;,&apos;&apos;))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Porte</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LegendaMapaGeografico__mdt/LegendaMapaGeografico__mdt.object-meta.xml
<CustomObject>
    <label>Legenda Mapa Geográfico</label>
    <pluralLabel>Legendas Mapa Geográfico</pluralLabel>
</CustomObject>

force-app/main/default/objects/LegendaMapaGeografico__mdt/fields/Cor__c.field-meta.xml
<CustomField>
    <fullName>Cor__c</fullName>
    <inlineHelpText>Cor em hexadecimal</inlineHelpText>
    <label>Cor</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LegendaMapaGeografico__mdt/fields/StatusLead__c.field-meta.xml
<CustomField>
    <fullName>StatusLead__c</fullName>
    <inlineHelpText>Nome API do Status do Lead</inlineHelpText>
    <label>Status do Lead</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/FiltroMapaGeo__c.field-meta.xml
<CustomField>
    <fullName>FiltroMapaGeo__c</fullName>
    <inlineHelpText>Último filtro utilizado na tela Mapa Geográfico</inlineHelpText>
    <label>Filtro Mapa Geo</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/MapGeographicLeadController.cls
public with sharing class MapGeographicLeadController {
    
    //TO DO fazer classe de TEST
    private final static List<LegendaMapaGeografico__mdt> legendas = [SELECT Id, MasterLabel, StatusLead__c, Cor__c FROM LegendaMapaGeografico__mdt];

    @AuraEnabled(cacheable=true)
    public static Boolean checkPermissionMap(){
        return FeatureManagement.checkPermission('FSL_Mapa_Lead_Geografico');
    }

    @AuraEnabled(cacheable=true)
    public static String verificarFiltrosAnteriores() {
        
        User usuario = [SELECT Id, FiltroMapaGeo__c FROM User WHERE Id = :UserInfo.getUserId()];
        String filtros = usuario.FiltroMapaGeo__c != null ? usuario.FiltroMapaGeo__c : '{}';
        return filtros;
    }

    @AuraEnabled
    public static void salvarFiltros(String inicio, String fim, List<String> status, List<String> canalEntrada, Boolean exCliente, List<String> tipoRegistro, List<String> porte, List<String> rating) {

        FiltrosMapGeo fmg = new FiltrosMapGeo();
        fmg.inicio = inicio;
        fmg.fim = fim;
        fmg.status = status;
        fmg.canalEntrada = canalEntrada;
        fmg.exCliente = exCliente;
        fmg.tipoRegistro = tipoRegistro;
        fmg.porte = porte;
        fmg.rating = rating;
        String filtros = JSON.serialize(fmg);
        
        User usuario = new User(Id = UserInfo.getUserId());
        usuario.FiltroMapaGeo__c = filtros;
        update usuario;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Lead> obtainLeads(List<String> status, List<String> canalEntrada, Boolean exCliente, List<String> tipoRegistro, List<String> porte, List<String> rating, String inicio, String fim) {
        
        String valueExCliente = exCliente == true ? 'Sim' : 'Não';

        Datetime dtInicio = Datetime.valueOf(inicio + ' 00:00:00');
        Datetime dtFim = Datetime.valueOf(fim + ' 00:00:00');
        dtFim = dtFim.addDays(1);
        
        return [SELECT Id, Name, LeadSource, Status, Owner.Name, Phone, Email, MobilePhone, Longitude__c, Latitude__c, Coordenadas__Longitude__s, Coordenadas__Latitude__s 
        FROM Lead 
        WHERE Longitude__c != null
        AND Status IN :status
        AND (CanalEntrada__c IN :canalEntrada OR CanalEntrada__c = null)
       /* AND ExCliente__c = :valueExCliente*/
        AND RecordType.DeveloperName IN :tipoRegistro
        AND Porte__c IN :porte
        AND (Rating IN :rating OR Rating = null)
        AND CreatedDate >= :dtInicio AND CreatedDate < :dtFim
        LIMIT 40000];
    }

    @AuraEnabled(cacheable=true)
    public static List<LegendaMapaGeografico__mdt> obtainLegends(){
        return legendas;
    }

    public class FiltrosMapGeo {

        public String inicio {get;set;}
        public String fim {get;set;}
        public List<String> status {get;set;}
        public List<String> canalEntrada {get;set;}
        public Boolean exCliente {get;set;}
        public List<String> tipoRegistro {get;set;}
        public List<String> porte {get;set;}
        public List<String> rating {get;set;}
        
    }
}