force-app/main/default/objects/Lead/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Inserir o CNPJ sem pontos, traços ou dígitos.</inlineHelpText>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Inserir o CPF sem pontos, traços ou dígitos.</inlineHelpText>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/CPFCNPJ__c.field-meta.xml
<CustomField>
    <fullName>CPFCNPJ__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>CPFCNPJ</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/NumeroVidas__c.field-meta.xml
<CustomField>
    <fullName>NumeroVidas__c</fullName>
    <label>Quantidade de Vidas Novas</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/PessoaFisica.recordType-meta.xml
<RecordType>
    <fullName>PessoaFisica</fullName>
    <active>true</active>
    <businessProcess>Varejo</businessProcess>
    <label>Pessoa Física</label>
</RecordType>

force-app/main/default/objects/Movimentacao__c/Movimentacao__c.object-meta.xml
<CustomObject>
    <label>Movimentação</label>
    <nameField>
        <displayFormat>MV-{0000000}</displayFormat>
        <label>Movimentação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movimentações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movimentacao__c/fields/CPFCNPJ__c.field-meta.xml
<CustomField>
    <fullName>CPFCNPJ__c</fullName>
    <label>CPFCNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Movimentacao__c/fields/CPFTitular__c.field-meta.xml
<CustomField>
    <fullName>CPFTitular__c</fullName>
    <description>Campo que especifica o CPF do titular em um dependente</description>
    <label>CPF do titular</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MovimentacaoUpdateBatchTest.cls
@isTest
public class MovimentacaoUpdateBatchTest {
    @TestSetup
    static void setup() {
        Movimentacao__c movimentacao1 = new Movimentacao__c(CPFCNPJ__c = '39527840015');
        insert movimentacao1;

        Movimentacao__c movimentacao2 = new Movimentacao__c(
            CPFCNPJ__c = '25888784000188',
            CPFTitular__c = '08492756012'
        );
        insert movimentacao2;

        Movimentacao__c movimentacao3 = new Movimentacao__c(CPFCNPJ__c = '37072381000124');
        insert movimentacao3;

        Lead lead1 = new Lead(
            LastName = 'MyLead1',
            MobilePhone = '31988887771',
            Phone = '31988887771',
            Email = 'MyLead1@email.com.br.test',
            CPF__c = '395.278.400-15',
            NumeroVidas__c = 10,
            RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName()
                .get('PessoaFisica')
                .getRecordTypeId()
        );
        insert lead1;

        Lead lead2 = new Lead(
            LastName = 'MyLead2',
            MobilePhone = '31988887772',
            Phone = '31988887772',
            Email = 'MyLead2@email.com.br.test',
            CPF__c = '084.927.560-12',
            NumeroVidas__c = 10,
            RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName()
                .get('PessoaFisica')
                .getRecordTypeId()
        );
        insert lead2;

        Lead lead3 = new Lead(
            LastName = 'MyLead3',
            MobilePhone = '31988887773',
            Phone = '31988887773',
            Email = 'MyLead3@email.com.br.test',
            CNPJ__c = '37.072.381/0001-24',
            NumeroVidas__c = 10,
            RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName()
                .get('PessoaFisica')
                .getRecordTypeId()
        );
        insert lead3;

        Lead lead4 = new Lead(
            LastName = 'MyLead4',
            MobilePhone = '31988887774',
            Phone = '31988887774',
            Email = 'MyLead4@email.com.br.test',
            CNPJ__c = '25.888.784/0001-88',
            NumeroVidas__c = 10,
            RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName()
                .get('PessoaFisica')
                .getRecordTypeId()
        );
        insert lead4;
    }

    @isTest
    static void testEcecuteMovimentacaoUpdateBatch() {
        Test.startTest();
        Database.executeBatch(new MovimentacaoUpdateBatch());
        Test.stopTest();
    }
}