force-app/main/default/objects/Lead/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Inserir o CNPJ sem pontos, traços ou dígitos.</inlineHelpText>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Inserir o CPF sem pontos, traços ou dígitos.</inlineHelpText>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/CPFCNPJ__c.field-meta.xml
<CustomField>
    <fullName>CPFCNPJ__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>CPFCNPJ</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/CANAL__c.field-meta.xml
<CustomField>
    <fullName>CANAL__c</fullName>
    <label>CANAL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CALL CENTER</fullName>
            </value>
            <value>
                <fullName>EQUIPE CORPORATIVA</fullName>
            </value>
            <value>
                <fullName>GVEN - CONSULTORES</fullName>
            </value>
            <value>
                <fullName>LOJAS AUTORIZADAS</fullName>
            </value>
            <value>
                <fullName>LOJAS PRÓPRIAS</fullName>
            </value>
            <value>
                <fullName>PROMOTORES</fullName>
            </value>
            <value>
                <fullName>NOVOS NEGOCIOS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadTriggerHandler.cls
public without sharing class LeadTriggerHandler extends TriggerHandler {
    
    //TO DO fazer classe de test

    public override void beforeInsert() {
        system.debug('1');
        LeadDomain.getInstance().setProprietarioOriginal((List<Lead>) Trigger.new);
        LeadDomain.getInstance().criaClone((List<Lead>) Trigger.new);

        Set<String> cpfcnpj = new Set<String>();
        Set<Id> ownerIds = new Set<Id>();
        
        for(Lead ld: (List<Lead>)Trigger.new){
            if( String.isNotBlank(ld.CPF__c)){
                cpfcnpj.add(ld.CPF__c.replaceAll('\\D',''));
            }else if(String.isNotBlank(ld.CNPJ__c)){
                cpfcnpj.add(ld.CNPJ__c.replaceAll('\\D',''));
            }
        }

        List<Lead> Leads = [SELECT Id, OwnerId FROM Lead WHERE CPFCNPJ__c IN :cpfcnpj];
       
        for(Lead ld: Leads){
            ownerIds.add(ld.OwnerId);
        }
        
        List<User> Users = [SELECT Id, Canal__c, Name FROM User WHERE Id IN :ownerIds];
        
       System.debug('cpfcnpj: ' + cpfcnpj); 
       System.debug('ownerIds: ' + ownerIds); 
        
        Map<Id, Lead> mapLead = new Map<Id, Lead>(Leads);
        Map<Id, User> mapUser = new Map<Id, User>(Users);
        
        System.debug('mapLead: ' + mapLead); 
        if(mapLead.isEmpty() == false){
            List<Lead> ld = Trigger.new;
            Integer index = 0;
            for(Id key : mapUser.keySet()) {
                User u = mapUser.get(key);
                string linebreak = '------------------------------------------------';
                string errMsg = 'Lead Duplicado. ' + linebreak + ' Proprietário da duplicata: ' + u.Name + ' // Canal: ' + u.Canal__c;
                ld[index].addError(errMsg, true);
                index++;
            }
        }
    }

    public override void beforeUpdate() {
        system.debug('2');
        LeadDomain.getInstance().setProprietarioOriginal((List<Lead>) Trigger.new);
    }

    public override void afterUpdate(){
        system.debug('3');
        LeadDomain.getInstance().sendRelationshipToAccount((List<Lead>) Trigger.new, (Map<Id, Lead>) Trigger.oldMap);
    }
}