force-app/main/default/objects/Lead/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <defaultValue>&quot;naotem@naotem.com&quot;</defaultValue>
    <inlineHelpText>Campo utilizado para o Marketing, não modificar o valor padrão.</inlineHelpText>
    <label>Email do cliente</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/NumeroVidas__c.field-meta.xml
<CustomField>
    <fullName>NumeroVidas__c</fullName>
    <label>Quantidade de Vidas Novas</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Carga__c.field-meta.xml
<CustomField>
    <fullName>Carga__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Carga</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Visitas</relationshipLabel>
    <relationshipName>CompromissosServicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/NumeroVidas__c.field-meta.xml
<CustomField>
    <fullName>NumeroVidas__c</fullName>
    <formula>Lead__r.NumeroVidas__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Número de Vidas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/ServiceResource__c.field-meta.xml
<CustomField>
    <fullName>ServiceResource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurso de serviço</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Compromissos de serviços</relationshipLabel>
    <relationshipName>Compromissos_de_servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Venda_Realizada__c.field-meta.xml
<CustomField>
    <fullName>Venda_Realizada__c</fullName>
    <label>Venda Realizada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Agendamentos</relationshipLabel>
    <relationshipName>Agendamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ServiceAppointmentTriggerHandlerTest.cls
@isTest
public class ServiceAppointmentTriggerHandlerTest {

    @testSetup
    static void setup(){
        Profile p = [SELECT Id FROM Profile WHERE Name LIKE '%Admin%' LIMIT 1]; 
    	User u = new User(
            Alias = 'standt', 
            Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', 
            LastName='Testing', 
            LanguageLocaleKey='en_US',        
            LocaleSidKey='en_US', 
            ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', 
            UserName='testusertest@testorgtest.com'
        );
        insert u;
        
        Lead ld = new Lead(
            LastName = 'MyLead',
            MobilePhone = '31988887777',
            Status = 'Captação',
            Email = 'mylead@email.com.br.test',
           // Email__c = 'mylead@email.com.br.test',
            NumeroVidas__c = 31
        );
        insert ld;
        
        ServiceResource rsc = new ServiceResource(
            IsActive = true,
            RelatedRecordId = u.Id,
            Name = 'User',
            ResourceType = 'T'
        );
        insert rsc;
        
        OperatingHours oh = new OperatingHours(
            Name = 'MyOpHours'
        );
        insert oh;

        ServiceTerritory terr = new ServiceTerritory(
            Name = 'MyTerr',
            OperatingHoursId = oh.Id,
            IsActive = true
        );
        insert terr;
        
        ServiceTerritoryMember mterr = new ServiceTerritoryMember(
            ServiceResourceId = rsc.Id,
            ServiceTerritoryId = terr.Id,
            EffectiveStartDate = System.now(),
            TerritoryType = 'P'
        );
        insert mterr;
        
        WorkOrder wo = new WorkOrder(
            Status = 'New',
            ServiceTerritoryId = terr.Id
        );
        insert wo;

        ServiceAppointment appt1 = new ServiceAppointment(
            ParentRecordId = wo.Id,
            EarliestStartTime = System.now().addDays(7),
            DueDate = System.now().addDays(8),
            SchedStartTime = System.now().addDays(7),
            SchedEndTime = System.now().addDays(8),
            ServiceTerritoryId = terr.Id,
            Carga__c = true,
            Lead__c = ld.Id,
            ServiceResource__c = rsc.Id
        );
        insert appt1;
        
        AssignedResource ar1 = new AssignedResource();
        ar1.ServiceAppointmentId = appt1.Id;
        ar1.ServiceResourceId = rsc.Id;
        
        insert ar1;


    }
   
    @isTest
    static void checkBusinessHoursTest(){
        ServiceAppointment appt = [SELECT Id FROM ServiceAppointment LIMIT 1];
        appt.Status = 'Scheduled';
        /*update appt;

        appt.Status = 'In Progress';
        update appt;

        Test.startTest();
        appt.Status = 'Completed';
        appt.Venda_Realizada__c = 'Sim';*/
        Test.startTest();
        try{
            update appt;
        }catch(Exception e){
            String message = e.getDmlMessage(0);
            System.debug('message'+message);
            System.assertEquals('O agendamento não pode ser concluído fora do horário de expediente!', message);
        }
        Test.stopTest();

    }
}