force-app/main/default/objects/Lead/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <defaultValue>&quot;naotem@naotem.com&quot;</defaultValue>
    <inlineHelpText>Campo utilizado para o Marketing, não modificar o valor padrão.</inlineHelpText>
    <label>Email do cliente</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/NumeroVidas__c.field-meta.xml
<CustomField>
    <fullName>NumeroVidas__c</fullName>
    <label>Quantidade de Vidas Novas</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/EmailsInteressados__c.field-meta.xml
<CustomField>
    <fullName>EmailsInteressados__c</fullName>
    <label>Emails Interessados</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Agendamentos</relationshipLabel>
    <relationshipName>Agendamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Campo fórmula para obter e disponibilizar os e-mails dos leads relacionados, dentro das atas.</description>
    <formula>Lead__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Atas</relationshipLabel>
    <relationshipName>Atas2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/NumeroVidas__c.field-meta.xml
<CustomField>
    <fullName>NumeroVidas__c</fullName>
    <description>Numero de pessoas que possuem plano</description>
    <label>Numero de vidas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/recordTypes/Call.recordType-meta.xml
<RecordType>
    <fullName>Call</fullName>
    <active>true</active>
    <label>Call</label>
</RecordType>

force-app/main/default/classes/IntegracaoServiceReportTest.cls
@isTest
public class IntegracaoServiceReportTest {
    
    @TestSetup
    static void setup(){
        Lead ld = new Lead(
            LastName = 'MyLead',
            MobilePhone = '31988887777',
            Status = 'Captação',
            Email = 'mylead@email.com.br.test',
            //Email__c = 'mylead@email.com.br.test',
            NumeroVidas__c = 31
        );
        insert ld;

        WorkOrder wo = new WorkOrder(
            Status = 'New',
            Lead__c = ld.Id,
            EmailsInteressados__c = 'emailtest@email.com.br.test'
        );
        insert wo;

        String call = Schema.SObjectType.WorkOrderLineItem.getRecordTypeInfosByDeveloperName().get('Call').getRecordTypeId();

        WorkOrderLineItem woli1 = new WorkOrderLineItem(
            WorkOrderId = wo.Id,
            Lead__c = ld.Id,       
            Status = 'New',
            RecordTypeId = call
        );
        insert woli1;
    }


    @isTest
    static void createServiceReportTest(){
        WorkOrderLineItem woli = [SELECT Id FROM WorkOrderLineItem LIMIT 1];

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new IntegracaoServiceReportMock());
        IntegracaoServiceReportService.createServiceReport(new List<String>{woli.Id});
        try{
            new IntegracaoRest().execute(null, null, null, null, null, null);
        }catch(Exception e){
            
        }
        Test.stopTest();
    }

    @isTest
    static void sendEmailServiceReportTest(){
        WorkOrderLineItem woli = [SELECT Id FROM WorkOrderLineItem LIMIT 1];
        ServiceReport sr = new ServiceReport();
        //sr.ContentVersionDocumentId = documents[0].Id ;
        sr.DocumentBody = Blob.valueOf('Test Content') ; 
        sr.DocumentContentType ='application/pdf';
        sr.DocumentName='Test';
        sr.ParentId = woli.Id ; 
        insert sr;

        Test.startTest();
        IntegracaoServiceReportService.sendEmailServiceReport(new List<String>{woli.Id});
        Test.stopTest();
    }
}