force-app/main/default/objects/Lead/fields/HouveAgendamento__c.field-meta.xml
<CustomField>
    <fullName>HouveAgendamento__c</fullName>
    <label>Houve agendamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/NumeroVidas__c.field-meta.xml
<CustomField>
    <fullName>NumeroVidas__c</fullName>
    <label>Quantidade de Vidas Novas</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ModalSchedulecomponentControllerTest.cls
@isTest
public without sharing class ModalSchedulecomponentControllerTest {
    
    @isTest
    public static void testaController() {

        Lead ld = new Lead();
        ld.FirstName = 'Eduardo';
        ld.LastName = 'Teste';
        ld.Email = 'edt@teste123.com';
        ld.Phone = '(31) 99999-8888';
        ld.HouveAgendamento__c = 'Sim';
        ld.NumeroVidas__c = 1;
        insert ld;

        Test.startTest();
        ModalScheduleComponentController.verificaMostrarModal(ld.Id);
        ModalScheduleComponentController.preencheCampoModal(ld.Id);
        Test.stopTest();

    }
}