force-app/main/default/objects/Opportunity/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <externalId>true</externalId>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DocId__c.field-meta.xml
<CustomField>
    <fullName>DocId__c</fullName>
    <description>Armazena o CPF (Plano Individual) ou CNPJ (Plano Empresarial) da Oportunidade</description>
    <externalId>true</externalId>
    <label>Documento Identificado da Integração</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/OpportunityDomain.cls
public without sharing class OpportunityDomain {
    
    private static OpportunityDomain instance = null;
    
    public static OpportunityDomain getInstance() {
        if (instance == null) {
            instance = new OpportunityDomain();
        }
        
        return instance;
    }

    public void copyToDocId(List<Opportunity> oppts){
        for(Opportunity oppt : oppts){
            if(String.isNotBlank(oppt.CPF__c)){
                oppt.DocId__c = oppt.CPF__c.replaceAll('\\D', '');
            }else
            if(String.isNotBlank(oppt.CNPJ__c)){
                oppt.DocId__c = oppt.CNPJ__c.replaceAll('\\D', '');
            }
        }
    }
}