force-app/main/default/objects/Opportunity/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <externalId>true</externalId>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHandlerTest.cls
@isTest
public class OpportunityTriggerHandlerTest {
    
    @TestSetup
    static void setup(){
        
    }

    @isTest
    static void copyToDocId(){
        Opportunity oppt = new Opportunity(
            Name = 'New Oppt',
            CloseDate = Date.today().addDays(10),
            CPF__c = '111.111.111-10',
            StageName = 'Elaboração de proposta'
        );

        Test.startTest();
        insert oppt;
        oppt.CPF__c = null;
        oppt.CNPJ__c = '99.999.999/9999-99';
        update oppt;
        Test.stopTest();
    }
}