force-app/main/default/objects/LogAcesso__c/LogAcesso__c.object-meta.xml
<CustomObject>
    <label>Log de Acesso</label>
    <nameField>
        <displayFormat>LA{000000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs de Acesso</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogAcesso__c/fields/IdRegistro__c.field-meta.xml
<CustomField>
    <fullName>IdRegistro__c</fullName>
    <label>Identificador</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogAcesso__c/fields/Objeto__c.field-meta.xml
<CustomField>
    <fullName>Objeto__c</fullName>
    <label>Objeto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogAcesso__c/fields/ObjetoAPI__c.field-meta.xml
<CustomField>
    <fullName>ObjetoAPI__c</fullName>
    <inlineHelpText>Nome de API do objeto</inlineHelpText>
    <label>Objeto API</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RastreioAcessoController.cls
public without sharing class RastreioAcessoController {


    @AuraEnabled
    public static void salvarLog(String idRegistro) {
        
        Id id = Id.valueOf(idRegistro);
        String nomeApiObjeto = id.getSObjectType().getDescribe().getName();
        String nomeObjeto = id.getSObjectType().getDescribe().getLabel();
        
        LogAcesso__c log = new LogAcesso__c();
        log.IdRegistro__c = idRegistro;
        log.ObjetoAPI__c = nomeApiObjeto;
        log.Objeto__c = nomeObjeto;
        insert log;
    }

    @AuraEnabled
    public static void salvarLogUtility(String identificador, String objeto, Boolean registro) {
        
        Id idRegistro = registro ? Id.valueOf(identificador) : null;
        String nomeApiObjeto = registro ? idRegistro.getSObjectType().getDescribe().getName() : '';
        String nomeObjeto = registro ? idRegistro.getSObjectType().getDescribe().getLabel() : objeto;
                
        LogAcesso__c log = new LogAcesso__c();
        log.IdRegistro__c = identificador;
        log.ObjetoAPI__c = nomeApiObjeto;
        log.Objeto__c = nomeObjeto;
        insert log;
    }
}