force-app/main/default/objects/LogAcesso__c/LogAcesso__c.object-meta.xml
<CustomObject>
    <label>Log de Acesso</label>
    <nameField>
        <displayFormat>LA{000000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs de Acesso</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogAcesso__c/fields/IdRegistro__c.field-meta.xml
<CustomField>
    <fullName>IdRegistro__c</fullName>
    <label>Identificador</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogAcesso__c/fields/Objeto__c.field-meta.xml
<CustomField>
    <fullName>Objeto__c</fullName>
    <label>Objeto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogAcesso__c/fields/ObjetoAPI__c.field-meta.xml
<CustomField>
    <fullName>ObjetoAPI__c</fullName>
    <inlineHelpText>Nome de API do objeto</inlineHelpText>
    <label>Objeto API</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExcluiLogsAcessoBatchTest.cls
@isTest
public without sharing class ExcluiLogsAcessoBatchTest {
    
    @testSetup
    public static void setup() {
        
        LogAcesso__c log = new LogAcesso__c();
        log.IdRegistro__c = 'idTeste';
        log.ObjetoAPI__c = 'objeto';
        log.Objeto__c = 'objeto';
        insert log;
    }
    
    @isTest 
    public static void testarBatch() {
        
        Date hoje = System.today();
		Date dataLimite = hoje.addMonths(1);
        
        Test.startTest();
        ExcluiLogsAcessoBatch elab = new ExcluiLogsAcessoBatch(dataLimite);
        Id batchId = Database.executeBatch(elab);
        Test.stopTest();
        
        List<LogAcesso__c> logs = new List<LogAcesso__c>();
        logs = [SELECT Id FROM LogAcesso__c];
        System.assertEquals(0, logs.size());
    }
}