force-app/main/default/objects/DailyDistance__c/DailyDistance__c.object-meta.xml
<CustomObject>
    <description>Objeto customizado para contabilidade de distância percorrida diariamente</description>
    <label>Distância Diária</label>
    <nameField>
        <displayFormat>D-{000000000}</displayFormat>
        <label>Código da distância diária</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distâncias Diárias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyDistance__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>DATEVALUE( $System.OriginDateTime )</defaultValue>
    <description>Dia da contabilidade de distância.</description>
    <inlineHelpText>Dia da contabilidade de distância.</inlineHelpText>
    <label>Data</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DailyDistance__c/fields/Distance__c.field-meta.xml
<CustomField>
    <fullName>Distance__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Distância percorrida (em metros).</description>
    <inlineHelpText>Distância percorrida (em metros).</inlineHelpText>
    <label>Distância percorrida em metros</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DailyDistance__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <description>Ultimo valor captado para a latitude do posicionamento informado.</description>
    <inlineHelpText>Ultimo valor captado para a latitude do posicionamento informado.</inlineHelpText>
    <label>Latitude</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DailyDistance__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <description>Ultimo valor captado para a longitude do posicionamento informado.</description>
    <inlineHelpText>Ultimo valor captado para a longitude do posicionamento informado.</inlineHelpText>
    <label>Longitude</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DailyDistance__c/fields/ServiceResourceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceResourceId__c</fullName>
    <description>Recurso de serviço (Field Service) para o qual os dados se referem.</description>
    <label>Pessoa</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Distâncias Diárias</relationshipLabel>
    <relationshipName>DailyDistances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RastreamentoRecursoServico__b/RastreamentoRecursoServico__b.object-meta.xml
<CustomObject>
    <label>Rastreamento do recurso de serviço</label>
    <pluralLabel>Rastreamentos do recurso de serviço</pluralLabel>
</CustomObject>

force-app/main/default/objects/RastreamentoRecursoServico__b/fields/DataLocalizacao__c.field-meta.xml
<CustomField>
    <fullName>DataLocalizacao__c</fullName>
    <label>Data de localização</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RastreamentoRecursoServico__b/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RastreamentoRecursoServico__b/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RastreamentoRecursoServico__b/fields/ServiceResource__c.field-meta.xml
<CustomField>
    <fullName>ServiceResource__c</fullName>
    <label>ServiceResource</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ServiceResourceDomain.cls
public without sharing class ServiceResourceDomain {
    
    private static ServiceResourceDomain instance = null;
    
    public static ServiceResourceDomain getInstance() {
        if (instance == null) {
            instance = new ServiceResourceDomain();
        }
        
        return instance;
    } 

    public void adjustOwnerServiceResource(List<ServiceResource> srs){

        for(ServiceResource sr : srs){
            if(sr.RelatedRecordId != null){
                sr.OwnerId = sr.RelatedRecordId;
            }
        }
    }

    public void saveGeolocation(List<ServiceResource> rsec, Map<Id, ServiceResource> oldRs){

        List<RastreamentoRecursoServico__b> rastreamentos = new List<RastreamentoRecursoServico__b>();
        for(ServiceResource sr : rsec){
            if(sr.LastKnownLocationDate != oldRs.get(sr.Id).LastKnownLocationDate){
                RastreamentoRecursoServico__b rrs = new RastreamentoRecursoServico__b();
                rrs.DataLocalizacao__c = sr.LastKnownLocationDate;
                rrs.Latitude__c = sr.LastKnownLatitude;
                rrs.Longitude__c = sr.LastKnownLongitude;
                rrs.ServiceResource__c = sr.Id;

                rastreamentos.add(rrs);
            }
        }

        saveRastreamento(JSON.serialize(rastreamentos));
    }

    @future
    public static void saveRastreamento(String jsonRast){
        List<RastreamentoRecursoServico__b> rastreamentos = (List<RastreamentoRecursoServico__b>) JSON.deserialize(jsonRast, List<RastreamentoRecursoServico__b>.class);
        if(!Test.isRunningTest()){
            database.insertImmediate(rastreamentos);
        }
    }

    @SuppressWarnings('PMD.ApexCRUDViolation')
    public void registerDistance(List<ServiceResource> serviceResourceList, Map<Id,ServiceResource> oldMapList){
        //Lista de disâncias diárias à serem atualizadas
        List<DailyDistance__c> dailyDistanceList = new List<DailyDistance__c>();
        
        //Precorre todos os registros de regustros em atualização
        for(ServiceResource serviceResourceRecord : serviceResourceList){

            //Se possuem dados de Latitude e Longitude
            if(serviceResourceRecord.LastKnownLatitude != null && 
                serviceResourceRecord.LastKnownLongitude != null &&
                oldMapList.get(serviceResourceRecord.Id).LastKnownLatitude != null && 
                oldMapList.get(serviceResourceRecord.Id).LastKnownLongitude != null){
                
                //Se os dados de posicionamento mudaram
                if(
                    serviceResourceRecord.LastKnownLatitude != oldMapList.get(serviceResourceRecord.Id).LastKnownLatitude ||
                    serviceResourceRecord.LastKnownLongitude != oldMapList.get(serviceResourceRecord.Id).LastKnownLongitude
                ){

                    //Adiciona à lista um registro de distância para cria/atualizar
                    dailyDistanceList.add(
                        calculatePositionUpdate(
                            serviceResourceRecord.Id, 
                            serviceResourceRecord.LastKnownLatitude,
                            serviceResourceRecord.LastKnownLongitude
                        ));
                }
            }
        }

        if(!dailyDistanceList.isEmpty()){
            saveDistancias(JSON.serialize(dailyDistanceList));
        }
    }
    
    @SuppressWarnings('PMD.ApexCRUDViolation')
    public DailyDistance__c calculatePositionUpdate(Id referenceId, Decimal latitude, Decimal longitude) {
        
        //Busca algum registro diário para a referência na data corrente
        DailyDistance__c dailyDistanceRecord = null;
        List<DailyDistance__c> records = [SELECT id, Distance__c, Latitude__c, Longitude__c FROM DailyDistance__c WHERE ServiceResourceId__c = :referenceId AND Date__c = :Date.today()];
        if(records != null && !records.IsEmpty()){
            dailyDistanceRecord = records[0];
        }

        //Se não existe um registro um diário
        if(dailyDistanceRecord == null){
            
            //Criar o registro com os prmeiros valores do dia
            dailyDistanceRecord = new DailyDistance__c();
            dailyDistanceRecord.ServiceResourceId__c = referenceId;
            dailyDistanceRecord.Date__c = Date.today();
            dailyDistanceRecord.Distance__c = 0;

        //Se não existe um registro diário
        } else {

            //calcular a distância e preencher o novo valor
            dailyDistanceRecord.Distance__c += calculateDistance(
                Decimal.valueOf(dailyDistanceRecord.Latitude__c),
                Decimal.valueOf(dailyDistanceRecord.Longitude__c),
                latitude,
                longitude
            );
        }

        System.debug('latitude');
        System.debug(latitude);
        System.debug('longitude');
        System.debug(longitude);
        
        //Atualiza os valores de última posição no registro diário
        dailyDistanceRecord.Latitude__c = String.valueOf(latitude);
        dailyDistanceRecord.Longitude__c = String.valueOf(longitude);
        System.debug('dailyDistanceRecord.Latitude__c ');
        System.debug(dailyDistanceRecord.Latitude__c );
        System.debug('dailyDistanceRecord.Longitude__c ');
        System.debug(dailyDistanceRecord.Longitude__c );

        //Cria ou atualiza o registro diário
        return dailyDistanceRecord;
    }

    @SuppressWarnings('PMD.ApexCRUDViolation')
    @future
    public static void saveDistancias(String jsonRast){
        List<DailyDistance__c> rastreamentos = (List<DailyDistance__c>) JSON.deserialize(jsonRast, List<DailyDistance__c>.class);
        if(!Test.isRunningTest()){
            database.upsert(rastreamentos);
        }
    }

    //Realiza o cálculo de distância em quilômetros entre dois pontos
    @SuppressWarnings('PMD.ExcessiveParameterList')
    public static Decimal calculateDistance(
        Decimal oldLatitude, 
        Decimal oldLongitude, 
        Decimal newLatitude, 
        Decimal newLongitude){

        //Geração do registro de localização
        Location oldLocation = Location.newInstance(oldLatitude,oldLongitude);
        Location newLocation = Location.newInstance(newLatitude,newLongitude);

        //Realiza o cálculo de distância entre as duas posições
        Decimal distance = Location.getDistance(oldLocation, newLocation, 'km');

        //Retorna ovalor da distância entre os dois ponteos
        return distance;
    }
}